#!/usr/bin/env python3
"""Type-check the LLVM backend on a machine that cannot build LLVM.

`src/codegen.rs` is behind `--features llvm`, which needs `llvm-sys 180`, which
needs LLVM 18 installed and is Linux/macOS only. So on Windows the file cannot
be compiled at all — and it has broken three times without anyone noticing,
twice because an AST node grew a field and the pattern in codegen.rs was left
naming too few.

But it can be *type-checked* anywhere, because llvm-sys's own source sits in the
cargo registry cache even where it cannot be compiled. This generates a
signature-only crate from that source — the same declarations, no library behind
them — points cargo at it, and runs `cargo check --features llvm`.

    python scripts/check_llvm_backend.py
    python scripts/check_llvm_backend.py --clean     # if it was interrupted

What this catches: every type error and every borrow error, in the whole file.
What it cannot catch: invalid IR, and a wrong answer. Those need Ubuntu and
`scripts/run_parity.sh`. Do not read a clean run here as "the backend works".

It is not a substitute for the `llvm-backend` CI job, which builds against the
real library. It is what makes the file editable on a machine that job does not
run on.
"""

import argparse
import glob
import io
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CRATE = os.path.join(ROOT, "etamil_compiler")
SHIM = os.path.join(CRATE, "target", "llvm-sys-shim")
CONFIG_DIR = os.path.join(CRATE, ".cargo")
CONFIG = os.path.join(CONFIG_DIR, "config.toml")
LOCK = os.path.join(CRATE, "Cargo.lock")
LOCK_BACKUP = os.path.join(CRATE, "target", "Cargo.lock.before-llvm-check")

# The only two files that touch llvm-sys.
# Every source that names an LLVM symbol, found rather than listed: a hardcoded
# list goes stale silently, and this one did — src/fileio/csv_handler.rs was
# deleted and the script then crashed on a missing file instead of checking
# anything.
def llvm_sources():
    found = []
    for base, _, files in os.walk(os.path.join(CRATE, "src")):
        for name in files:
            if not name.endswith(".rs"):
                continue
            path = os.path.join(base, name)
            with io.open(path, encoding="utf-8") as handle:
                if "llvm_sys" in handle.read():
                    found.append(path)
    return sorted(found)

# Type aliases and enums the declarations refer to. Over-broad on purpose: an
# alias nothing uses costs nothing, and a missing one is a confusing error.
ALIASES = [
    "LLVMContextRef", "LLVMModuleRef", "LLVMBuilderRef", "LLVMValueRef",
    "LLVMTypeRef", "LLVMBasicBlockRef", "LLVMMetadataRef", "LLVMNamedMDNodeRef",
    "LLVMUseRef", "LLVMAttributeRef", "LLVMDiagnosticInfoRef", "LLVMComdatRef",
    "LLVMModuleFlagEntry", "LLVMValueMetadataEntry", "LLVMOperandBundleRef",
    "LLVMJITEventListenerRef",
]

ENUMS = [
    "LLVMIntPredicate", "LLVMRealPredicate", "LLVMLinkage", "LLVMOpcode",
    "LLVMTypeKind", "LLVMVisibility", "LLVMUnnamedAddr", "LLVMDLLStorageClass",
    "LLVMCallConv", "LLVMValueKind", "LLVMAtomicOrdering", "LLVMAtomicRMWBinOp",
    "LLVMDiagnosticSeverity", "LLVMInlineAsmDialect", "LLVMModuleFlagBehavior",
    "LLVMThreadLocalMode", "LLVMTailCallKind", "LLVMGEPNoWrapFlags",
]

# llvm-sys features etamil_compiler asks for. Cargo refuses a path override that
# does not offer them, so the shim has to declare them even though they do
# nothing here.
FEATURES = [
    "prefer-dynamic", "no-llvm-linking", "strict-versioning",
    "disable-alltargets-init", "force-static", "force-dynamic",
]

CARGO_TOML = (
    '# Generated by scripts/check_llvm_backend.py. Not part of the build.\n'
    '[package]\nname = "llvm-sys"\nversion = "180.0.0"\nedition = "2021"\n\n'
    '[lib]\nname = "llvm_sys"\npath = "src/lib.rs"\n\n'
    "[features]\n" + "".join("%s = []\n" % f for f in FEATURES) + "\n"
    '[dependencies]\nlibc = "0.2"\nanyhow = "1"\n'
)


def find_llvm_sys():
    found = glob.glob(os.path.expanduser("~/.cargo/registry/src/*/llvm-sys-180.*"))
    if not found:
        sys.exit(
            "llvm-sys 180 is not in the cargo registry cache, so there are no\n"
            "signatures to copy. Run `cargo fetch` in etamil_compiler first."
        )
    return sorted(found)[-1]


def symbols_used():
    names = set()
    for path in llvm_sources():
        text = io.open(path, encoding="utf-8").read()
        names.update(re.findall(r"\bLLVM[A-Za-z0-9_]+", text))
    return names


def generate(source):
    core = io.open(os.path.join(source, "src/core.rs"), encoding="utf-8").read()
    lib = io.open(os.path.join(source, "src/lib.rs"), encoding="utf-8").read()

    declarations = {}
    for match in re.finditer(
        r"pub fn (LLVM\w+)\((?:[^;]*?)\)(?:\s*->\s*[^;]+?)?;", core, re.S
    ):
        declarations.setdefault(match.group(1), match.group(0))

    wanted = symbols_used()
    keep = {name for name in wanted if name in declarations}
    # A signature may name another declared function as a callback parameter.
    for _ in range(3):
        for name in list(keep):
            for other in re.findall(r"\bLLVM\w+", declarations[name]):
                if other in declarations:
                    keep.add(other)

    # The aliases live in llvm-sys's own `prelude`, so they name their targets
    # through `super::`. At crate root they must not.
    aliases = []
    for name in ALIASES:
        match = re.search(r"pub type %s = [^;]+;" % name, lib)
        if match:
            aliases.append(match.group(0).replace("super::", ""))
    opaque = sorted({re.search(r"\*mut (\w+)", a).group(1) for a in aliases})

    enums = []
    for name in ENUMS:
        match = re.search(r"pub enum %s \{.*?\n\}" % name, lib, re.S)
        if match:
            enums.append(
                "#[repr(C)]\n#[derive(Clone, Copy, Debug, PartialEq)]\n" + match.group(0)
            )

    out = [
        "//! A stand-in for llvm-sys 180: the same signatures, nothing behind them.",
        "//!",
        "//! Generated by scripts/check_llvm_backend.py from llvm-sys's own source, so",
        "//! it cannot disagree with the real crate about a signature. Never committed,",
        "//! never linked, and it would not run if it were.",
        "#![allow(non_snake_case, non_camel_case_types, dead_code)]",
        "",
        "pub type LLVMBool = ::libc::c_int;",
    ]
    out += ["pub enum %s {}" % name for name in opaque]
    out += [""] + aliases + [""] + enums + [""]
    out += [
        "pub mod prelude {",
        "    pub use super::{LLVMBool, %s};"
        % ", ".join(sorted(re.search(r"pub type (\w+)", a).group(1) for a in aliases)),
        "}",
        "",
        "pub mod core {",
        "    use super::prelude::*;",
        "    use super::*;",
        '    extern "C" {',
    ]
    for name in sorted(keep):
        out += ["        " + line.strip() for line in declarations[name].splitlines()]
    out += ["    }", "}", ""]

    os.makedirs(os.path.join(SHIM, "src"), exist_ok=True)
    io.open(os.path.join(SHIM, "src/lib.rs"), "w", encoding="utf-8", newline="\n").write(
        "\n".join(out) + "\n"
    )
    io.open(os.path.join(SHIM, "Cargo.toml"), "w", encoding="utf-8", newline="\n").write(
        CARGO_TOML
    )

    missing = sorted(
        name
        for name in wanted
        if name not in declarations
        and name not in opaque
        and not any(name in a for a in aliases)
        and not any(name in e for e in enums)
    )
    return len(keep), missing


def clean():
    """Put the checkout back. Cargo may rewrite Cargo.lock through an override."""
    if os.path.exists(CONFIG):
        os.remove(CONFIG)
    if os.path.isdir(CONFIG_DIR) and not os.listdir(CONFIG_DIR):
        os.rmdir(CONFIG_DIR)
    if os.path.exists(LOCK_BACKUP):
        shutil.copyfile(LOCK_BACKUP, LOCK)
        os.remove(LOCK_BACKUP)
    shutil.rmtree(SHIM, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--clean",
        action="store_true",
        help="undo an interrupted run: remove the override and restore Cargo.lock",
    )
    arguments = parser.parse_args()

    if arguments.clean:
        clean()
        print("cleaned up.")
        return 0

    kept, missing = generate(find_llvm_sys())
    print("shim: %d declarations" % kept)
    if missing:
        # Not fatal: cargo will say exactly what is unresolved, which is a
        # better error than anything this script could invent.
        print("  not found in llvm-sys, expect an error naming it: %s" % ", ".join(missing))

    os.makedirs(CONFIG_DIR, exist_ok=True)
    shutil.copyfile(LOCK, LOCK_BACKUP)
    io.open(CONFIG, "w", encoding="utf-8", newline="\n").write(
        "# Generated by scripts/check_llvm_backend.py; deleted when it finishes.\n"
        'paths = ["%s"]\n' % SHIM.replace("\\", "/")
    )

    try:
        finished = subprocess.run(
            ["cargo", "check", "--features", "llvm", "--all-targets"],
            cwd=CRATE,
        )
    finally:
        clean()

    if finished.returncode == 0:
        print()
        print("Types check. That is not the same as working:")
        print("  the IR is unverified and the answers uncompared until")
        print("  scripts/run_parity.sh runs on Linux or macOS.")
    return finished.returncode


if __name__ == "__main__":
    sys.exit(main())
