#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Mohammed Maruff (Esan Maruff) <esan@etamil.in>
"""Regenerate the VS Code extension's language data from the compiler itself.

The extension used to carry a hand-written keyword list. It drifted: by the
time anyone checked, 67 of the lexer's 201 keywords were missing from the
grammar and 28 romanized spellings were the pre-`Z` scheme, so the spellings
the editor highlighted were exactly the ones the compiler rejected. Nothing
could have caught that, because nothing derived one from the other.

Now everything that can be derived is. Run from the repository root after
changing the token list, the builtins, or nUlakam:

    python scripts/generate_editor_support.py
    python scripts/generate_editor_support.py --check   # CI: fail on drift

Written outputs:

    eTamil_Code/syntaxes/etamil.tmLanguage.json   TextMate grammar
    eTamil_Code/src/generated/language-data.ts    completions, hover, symbols

Three things are read, and nothing is duplicated by hand:

  lexer.rs        every keyword and every spelling of it, grouped by the
                  section comments the lexer already uses.
  parser.rs       `is_identifier_like` and `is_type_token`, which decide
                  whether a word is reserved or is usable as a name. This is
                  the distinction the old grammar got backwards — it
                  highlighted மாறி and நிலை as declarations when both are
                  ordinary names to the parser.
  interpreter.rs  the builtin functions, with their arity and doc comment.
  nUlakam/*.qmz   the standard library's own செயல் definitions.

What is *not* derived is the shape of each statement — `(cond) எனில் { }`
cannot be inferred from a token name. Those templates live in SNIPPETS below
and are the one part of this file that must be kept true by hand; every one
of them is exercised by tests/test_snippets.py.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEXER = ROOT / "etamil_compiler" / "src" / "lexer.rs"
PARSER = ROOT / "etamil_compiler" / "src" / "parser.rs"
INTERPRETER = ROOT / "etamil_compiler" / "src" / "vm" / "interpreter.rs"
NULAKAM = ROOT / "nUlakam"

EXT = ROOT / "eTamil_Code"
GRAMMAR_OUT = EXT / "syntaxes" / "etamil.tmLanguage.json"
DATA_OUT = EXT / "src" / "generated" / "language-data.ts"
PYGMENTS_OUT = (
    ROOT / "eTamil_Pygments" / "etamil_pygments" / "_etamil_builtins.py"
)
# Rouge is what GitHub Pages and Jekyll highlight with, so this is the lexer
# that renders eTamil on the language's own site.
ROUGE_OUT = ROOT / "eTamil_Rouge" / "lib" / "rouge" / "lexers" / "etamil.rb"
# highlight.js covers web documentation and the browser playground, neither of
# which can run Pygments or Rouge.
HIGHLIGHTJS_OUT = ROOT / "eTamil_HighlightJS" / "src" / "languages" / "etamil.js"
# tree-sitter is what Neovim, Helix and Zed parse with, and what GitHub uses
# for code navigation. Only the vocabulary is generated; the grammar's
# structure is hand-written, because the shape of a statement cannot be
# derived from a token table.
TREESITTER_OUT = ROOT / "tree-sitter-etamil" / "keywords.js"

TAMIL = "஀-௿"
# The same identifier shape the lexer accepts, so the grammar cannot scope
# something the compiler would refuse to tokenize.
IDENT = f"[a-zA-Z_{TAMIL}][a-zA-Z0-9_{TAMIL}]*"

BANNER = "Generated by scripts/generate_editor_support.py — do not edit by hand."


# --------------------------------------------------------------------------
# Scope assignment
# --------------------------------------------------------------------------
#
# A reserved word gets a keyword scope; a word the parser accepts as a name
# gets `support.type.domain`, because that is what it is — domain vocabulary
# the author may reuse. README says so explicitly: "தொகை is a perfectly good
# name for an amount." Colouring those as reserved told the reader the
# opposite of the truth.

# Section comment in lexer.rs -> scope for the reserved words in it.
SECTION_SCOPES = {
    "Core Financial & Accounting": "support.type.domain.etamil",
    "Transactions & Documents": "support.type.domain.etamil",
    "Money Movement": "support.type.domain.etamil",
    "Income & Costs": "support.type.domain.etamil",
    "Accounts, Reporting & Audit": "support.type.domain.etamil",
    "Indian Taxation": "support.type.domain.etamil",
    "Variables & Data Types": "storage.type.etamil",
    "Control Flow": "keyword.control.etamil",
    "Functions": "keyword.declaration.function.etamil",
    "Iteration": "keyword.control.loop.etamil",
    "Modules": "keyword.control.import.etamil",
    "File I/O Operations": "support.function.fileio.etamil",
    "Database Connectivity Operations": "support.function.database.etamil",
    "Database Types": "support.constant.database.etamil",
    "Database Operations": "keyword.other.database.etamil",
    "Database Clauses & Keywords": "keyword.other.sql.etamil",
    "REST API & HTTP": "keyword.other.http.etamil",
    "Encryption & Security": "keyword.other.security.etamil",
    "Logical Operators": "keyword.operator.logical.etamil",
}

# Where the section is too coarse. Keyed by the lexer's token name.
TOKEN_SCOPES = {
    "If": "keyword.control.conditional.etamil",
    "Else": "keyword.control.conditional.etamil",
    "Loop": "keyword.control.loop.etamil",
    "Print": "keyword.other.io.etamil",
    "Input": "keyword.other.io.etamil",
    "Return": "keyword.control.flow.return.etamil",
    "True": "constant.language.boolean.etamil",
    "False": "constant.language.boolean.etamil",
    "Null": "constant.language.null.etamil",
    "HttpGet": "support.constant.http-method.etamil",
    "HttpPost": "support.constant.http-method.etamil",
    "HttpPut": "support.constant.http-method.etamil",
    "HttpDelete": "support.constant.http-method.etamil",
    "HttpPatch": "support.constant.http-method.etamil",
    "HttpOptions": "support.constant.http-method.etamil",
    "HttpHead": "support.constant.http-method.etamil",
    "Route": "keyword.control.route.etamil",
    "Every": "keyword.control.every.etamil",
    "Response": "keyword.other.response.etamil",
}

# Reserved words the parser recognizes but no statement consumes, so the only
# thing an author can get out of them is "expected a statement". They stay
# highlighted — they really are reserved, and pretending otherwise would be a
# different lie — but the extension's hover says so, which is why the flag is
# carried through to the generated data rather than being dropped here.
NO_SYNTAX = {
    "Database", "DBSearch", "Table", "Collection", "Row", "Column", "Key",
    "PrimaryKey", "ForeignKey", "Index", "AlterTable", "DropTable",
    "OrderBy", "GroupBy", "Join", "Left", "Right", "Inner", "Outer",
    "Distinct", "Limit", "Offset",
    "API", "Endpoint", "Request", "Header", "Body", "Param", "QueryParam",
    "PathParam", "URL", "Host", "Port", "Method", "StatusCode",
    "StatusMessage", "Auth", "BearerToken", "ContentType", "Serve",
    "Encrypt", "Decrypt", "Password", "EncryptionKey",
    "File", "CSV", "Read", "Write", "Open", "Close", "FileLines",
    "SQL", "NoSQL", "MongoDB", "Redis", "JSONdb",
    "Let",
    "JSONBody",
}

# Statement shapes. Two templates per entry so a romanized author gets
# romanized placeholders: half of "Tamil semantics you can type on a plain
# keyboard" is the romanized path, and the old extension only served Tamil.
# `{kw}` is replaced with the spelling the author actually typed.
SNIPPETS = {
    "If": (
        "(${1:நிபந்தனை}) {kw} {\n\t$0\n}",
        "(${1:condition}) {kw} {\n\t$0\n}",
    ),
    "Else": ("{kw} {\n\t$0\n}", "{kw} {\n\t$0\n}"),
    "Loop": (
        "(${1:எண்ணி} < ${2:10}) {kw} {\n\t$0\n}",
        "(${1:i} < ${2:10}) {kw} {\n\t$0\n}",
    ),
    "Print": ("{kw} ${1:மதிப்பு};", "{kw} ${1:value};"),
    "Input": ("{kw} ${1:மாறி};", "{kw} ${1:name};"),
    "Function": (
        "{kw} ${1:பெயர்}(${2:அளவுரு}) {\n\t$0\n}",
        "{kw} ${1:name}(${2:param}) {\n\t$0\n}",
    ),
    "Return": ("{kw} ${1:மதிப்பு};", "{kw} ${1:value};"),
    "ForEach": (
        "{kw} ${1:உறுப்பு} இல் ${2:வரிசை} {\n\t$0\n}",
        "{kw} ${1:item} il ${2:items} {\n\t$0\n}",
    ),
    "Import": ('{kw} "${1:nUlakam/col.qmz}";', '{kw} "${1:nUlakam/col.qmz}";'),
    "IntegerType": ("{kw} ${1:பெயர்} = ${2:0};", "{kw} ${1:name} = ${2:0};"),
    "FloatType": ("{kw} ${1:பெயர்} = ${2:0.0};", "{kw} ${1:name} = ${2:0.0};"),
    "StringType": ('{kw} ${1:பெயர்} = "${2:உரை}";', '{kw} ${1:name} = "${2:text}";'),
    "TextType": ('{kw} ${1:பெயர்} = "${2:உரை}";', '{kw} ${1:name} = "${2:text}";'),
    # An array, record or boolean declaration must carry an initializer: a
    # bare `அணி x;` is rejected today, because the parser supplies 0 as the
    # implicit value and the checker holds that zero against the declared
    # type. Snippets that emitted the bare form produced a type error.
    "BoolType": ("{kw} ${1:பெயர்} = ${2:மெய்};", "{kw} ${1:name} = ${2:mey};"),
    "ArrayType": ("{kw} ${1:பெயர்} = [$2];", "{kw} ${1:name} = [$2];"),
    "ObjectType": (
        "{kw} ${1:பெயர்} = {${2:புலம்}: $3};",
        "{kw} ${1:name} = {${2:field}: $3};",
    ),
    "DataType": (
        "{kw} ${1:பெயர்} = {${2:புலம்}: $3};",
        "{kw} ${1:name} = {${2:field}: $3};",
    ),
    "DateType": ('{kw} ${1:பெயர்} = "${2:2026-04-01}";', '{kw} ${1:name} = "${2:2026-04-01}";'),
    "FileOpen": ('{kw} "${1:kOppu.txt}", "${2|read,write,append|}";', '{kw} "${1:file.txt}", "${2|read,write,append|}";'),
    "FileClose": ('{kw} "${1:kOppu.txt}";', '{kw} "${1:file.txt}";'),
    "FileWrite": ('{kw} "${1:kOppu.txt}", ${2:தரவு};', '{kw} "${1:file.txt}", ${2:data};'),
    "FileRead": ('{kw} "${1:kOppu.txt}", ${2:தரவு};', '{kw} "${1:file.txt}", ${2:data};'),
    "ReadCSV": ('{kw} "${1:qaravu.csv}", ${2:மொத்தம்};', '{kw} "${1:data.csv}", ${2:total};'),
    "WriteCSV": ('{kw} "${1:qaravu.csv}", ${2:நிரை};', '{kw} "${1:data.csv}", ${2:row};'),
    "DBConnect": ('{kw} ${1|சீகுலைட்,போச்குரசீகுல்,மைசீகுல்|}, "${2:kaNakku.db}";', '{kw} ${1|cIkulYt,pOckuracIkul,mYcIkul|}, "${2:kaNakku.db}";'),
    "DBDisconnect": ("{kw} ${1|சீகுலைட்,போச்குரசீகுல்,மைசீகுல்|};", "{kw} ${1|cIkulYt,pOckuracIkul,mYcIkul|};"),
    "DBQuery": (
        '{kw} "${1:SELECT * FROM pativukaL WHERE vakY = ?}", [${2:"வரவு"}], ${3:நிரைகள்};',
        '{kw} "${1:SELECT * FROM pativukaL WHERE vakY = ?}", [${2:"varavu"}], ${3:rows};',
    ),
    "DBExecute": (
        '{kw} "${1:INSERT INTO pativukaL(qokY) VALUES(?)}", [${2:1500}];',
        '{kw} "${1:INSERT INTO pativukaL(qokY) VALUES(?)}", [${2:1500}];',
    ),
    "Route": (
        '{kw} ${1|பெறு,பதி,இடு,அழி|}, "${2:/kaNakku/:id}" {\n\tபதில் 200, ${3:"ok"};\n}',
        '{kw} ${1|peRu,paqi,itu,azi|}, "${2:/kaNakku/:id}" {\n\tpaDil 200, ${3:"ok"};\n}',
    ),
    "Every": (
        '{kw} ${1:3600} {\n\t${2:அச்சு "ஒவ்வொரு மணிநேரமும்";}\n}',
        '{kw} ${1:3600} {\n\t${2:accu "every hour";}\n}',
    ),
    "Response": ('{kw} ${1:200}, ${2:"ok"};', '{kw} ${1:200}, ${2:"ok"};'),
    "StartServer": ('{kw} "${1:127.0.0.1}", ${2:8080};', '{kw} "${1:127.0.0.1}", ${2:8080};'),
    "Select": (
        "{kw} ${1:peyar} இதனில் ${2:pativukaL};",
        "{kw} ${1:peyar} iqaZil ${2:pativukaL};",
    ),
    # These four parse but the VM refuses them, so the template carries the
    # warning rather than leaving the author to discover it at run time.
    "CreateTable": (
        '{kw} ${1:pativukaL}, {${2:qokY}: "${3:TEXT}"};  // VM: not implemented — use தளம்_செய்',
        '{kw} ${1:pativukaL}, {${2:qokY}: "${3:TEXT}"};  // VM: not implemented — use qaLam_cey',
    ),
    "DBInsert": (
        '{kw} ${1:pativukaL}, {${2:qokY}: ${3:1500}};  // VM: not implemented — use தளம்_செய்',
        '{kw} ${1:pativukaL}, {${2:qokY}: ${3:1500}};  // VM: not implemented — use qaLam_cey',
    ),
    "DBUpdate": (
        '{kw} ${1:pativukaL}, {${2:qokY}: ${3:1500}};  // VM: not implemented — use தளம்_செய்',
        '{kw} ${1:pativukaL}, {${2:qokY}: ${3:1500}};  // VM: not implemented — use qaLam_cey',
    ),
    "DBDelete": (
        "{kw} ${1:pativukaL}, ${2:நிபந்தனை};  // VM: not implemented — use தளம்_செய்",
        "{kw} ${1:pativukaL}, ${2:condition};  // VM: not implemented — use qaLam_cey",
    ),
    "StopServer": ("{kw};", "{kw};"),
}

# Reserved words that are legitimately not statement-initial — clause words,
# operators, literals, and the names of methods and backends that appear as
# arguments inside another statement's template. Listing them keeps the
# generator's "no template yet" report meaningful.
NOT_A_STATEMENT = {
    "And", "Or", "Not",
    "True", "False", "Null",
    "In", "From", "Where",
    "HttpGet", "HttpPost", "HttpPut", "HttpDelete", "HttpPatch",
    "HttpOptions", "HttpHead",
    "SQLite", "MySQL", "PostgreSQL",
}


def die(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(2)


def is_tamil(text: str) -> bool:
    return any("஀" <= ch <= "௿" for ch in text)


# --------------------------------------------------------------------------
# Reading the compiler
# --------------------------------------------------------------------------
def read_tokens() -> list[dict]:
    """Every keyword in lexer.rs, in declaration order, tagged with section."""
    tokens: list[dict] = []
    section = ""
    for line in LEXER.read_text(encoding="utf-8").splitlines():
        heading = re.match(r"^\s*//\s*---\s*(.+?)\s*---", line)
        if heading:
            # "Control Flow (Your Updated Syntax)" -> "Control Flow"
            section = re.sub(r"\s*\(.*?\)\s*$", "", heading.group(1)).strip()
            continue
        entry = re.search(r'#\[regex\("([^"]+)"\)\]\s*(\w+)', line)
        if entry:
            tokens.append(
                {
                    "token": entry.group(2),
                    "forms": entry.group(1).split("|"),
                    "section": section,
                }
            )
    if not tokens:
        die(f"no keywords found in {LEXER}")
    return tokens


def read_parser_classification() -> tuple[set[str], set[str]]:
    """The parser's own answer to "may this word be a name?".

    Returns (not_a_name, type_keywords). Derived rather than restated: the
    grammar's job is to reflect the parser, and a second hand-kept copy of
    this list is what went wrong last time.
    """
    source = PARSER.read_text(encoding="utf-8")

    body = re.search(
        r"fn is_identifier_like\(token: &Token\) -> bool \{(.*?)\n    \}",
        source,
        re.S,
    )
    if not body:
        die("could not find is_identifier_like in parser.rs")
    # Every arm ending in `=> false` names words that cannot be identifiers.
    not_a_name: set[str] = set()
    for arm in re.findall(r"^(.*?)=>\s*false\s*,", body.group(1), re.M):
        not_a_name.update(re.findall(r"Token::(\w+)", arm))
    if not not_a_name:
        die("is_identifier_like matched no `=> false` arms")

    types = re.search(
        r"fn is_type_token\(token: &Token\) -> bool \{(.*?)\n    \}", source, re.S
    )
    if not types:
        die("could not find is_type_token in parser.rs")
    type_keywords = set(re.findall(r"Token::(\w+)", types.group(1)))

    return not_a_name, type_keywords


def read_builtins() -> list[dict]:
    """Host builtins from the interpreter's call_builtin match."""
    lines = INTERPRETER.read_text(encoding="utf-8").splitlines()
    builtins: list[dict] = []

    for index, line in enumerate(lines):
        arm = re.match(r'^\s+("(?:[^"]+)"(?:\s*\|\s*"[^"]+")+)\s*=>\s*\{', line)
        if not arm:
            continue
        forms = re.findall(r'"([^"]+)"', arm.group(1))
        if not is_tamil(forms[0]):
            continue  # a string match that is not a builtin name

        # The doc convention here is a comment block directly above the arm,
        # whose first useful line reads `// நீளம்(...) — what it does`.
        doc: list[str] = []
        cursor = index - 1
        while cursor >= 0:
            stripped = lines[cursor].strip()
            if not stripped.startswith("//"):
                break
            doc.append(stripped.lstrip("/").strip())
            cursor -= 1
        doc.reverse()

        # Arity, where the arm states it.
        arity = None
        for probe in lines[index : index + 6]:
            want = re.search(r"expect_args\(name,\s*&args,\s*(\d+)\)", probe)
            if want:
                arity = int(want.group(1))
                break

        builtins.append(
            {
                "name": forms[0],
                "forms": forms,
                "doc": pick_doc(doc, forms[0]),
                "arity": arity,
            }
        )

    if not builtins:
        die("no builtins found in interpreter.rs")
    return builtins


def unmark(text: str) -> str:
    """Drop the `__` marks an English comment carries.

    A comment written in English is wrapped `// __like this__` so that an
    editor showing the file in the eTamil font knows to draw those letters as
    Latin rather than as Tamil — `docs/reference/SCRIPT_RULES.md`. The marks
    are addressed to the editor, not to whoever reads a tooltip, so they come
    off here. Without this every hover in the extension grew a `__` at each
    end.
    """
    text = text.strip()
    if text.startswith("__") and text.endswith("__") and len(text) > 4:
        return text[2:-2].strip()
    return text


def pick_doc(doc_lines: list[str], name: str) -> str:
    """The line of a comment block that describes `name`, else the first."""
    for line in doc_lines:
        if line.startswith(name):
            return line
    for line in doc_lines:
        if line and not line.startswith("---"):
            return line
    return ""


def read_stdlib() -> list[dict]:
    """Every செயல் the standard library defines, with params and doc."""
    functions: list[dict] = []

    # Sort the POSIX string rather than the Path. Path ordering is
    # case-insensitive on Windows and case-sensitive everywhere else, so
    # sorting Path objects makes the output depend on which machine ran
    # this — aNi.qmz and AvaNam.qmz swap places, and CI then rejects a
    # file that was correct when it was generated.
    for path in sorted(NULAKAM.rglob("*.qmz"), key=lambda p: p.as_posix()):
        module = path.relative_to(ROOT).as_posix()
        lines = path.read_text(encoding="utf-8").splitlines()

        for index, line in enumerate(lines):
            if not re.match(rf"^\s*(?:செயல்|ceyal|_fn)\s+{IDENT}\s*\(", line):
                continue
            # A long parameter list wraps. Join forward to the closing paren,
            # or the 14 widest functions in the accounting framework — the
            # ones most worth completing — go missing.
            header = line
            probe = index
            while ")" not in header and probe + 1 < len(lines):
                probe += 1
                header += " " + lines[probe].strip()
            define = re.match(
                rf"^\s*(?:செயல்|ceyal|_fn)\s+({IDENT})\s*\((.*?)\)", header
            )
            if not define:
                continue
            name = define.group(1)
            params = [p.strip() for p in define.group(2).split(",") if p.strip()]

            doc: list[str] = []
            cursor = index - 1
            while cursor >= 0:
                stripped = lines[cursor].strip()
                if not stripped.startswith("//"):
                    break
                doc.append(unmark(stripped.lstrip("/").strip()))
                cursor -= 1
            doc.reverse()

            functions.append(
                {
                    "name": name,
                    "forms": [name],
                    "params": params,
                    "doc": pick_doc(doc, name),
                    "module": module,
                    # 1-based, so Go to Definition can open the library at the
                    # செயல் line rather than at the top of the file.
                    "line": index + 1,
                }
            )

    if not functions:
        die(f"no செயல் definitions found under {NULAKAM}")
    return functions


# --------------------------------------------------------------------------
# Classification
# --------------------------------------------------------------------------
def classify(tokens: list[dict]) -> list[dict]:
    not_a_name, type_keywords = read_parser_classification()

    for entry in tokens:
        token = entry["token"]
        # `take_name` accepts a token when it is identifier-like *and* not a
        # type keyword, so a type keyword is equally unusable as a name even
        # though is_identifier_like says nothing about it. Reporting only the
        # first half would tell an author that `சொல் உரை = "x";` is fine.
        entry["reserved"] = token in not_a_name or token in type_keywords
        entry["no_syntax"] = token in NO_SYNTAX

        if token in TOKEN_SCOPES:
            entry["scope"] = TOKEN_SCOPES[token]
        elif token in type_keywords:
            entry["scope"] = "storage.type.etamil"
        elif not entry["reserved"]:
            # Usable as a name, so not a keyword however domain-specific it
            # looks. `support.` reads as vocabulary, not syntax.
            entry["scope"] = "support.type.domain.etamil"
        else:
            entry["scope"] = SECTION_SCOPES.get(
                entry["section"], "keyword.other.etamil"
            )

    return tokens


# --------------------------------------------------------------------------
# Grammar
# --------------------------------------------------------------------------
def word_pattern(forms: list[str]) -> str:
    """A \\b-anchored alternation, longest first.

    Longest-first is not strictly required — the trailing \\b already forces
    the regex to backtrack from கோப்பு to கோப்பு_திற — but relying on that is
    a trap for whoever edits this next.
    """
    ordered = sorted(set(forms), key=lambda form: (-len(form), form))
    return r"\b(?:" + "|".join(re.escape(f) for f in ordered) + r")\b"


def build_grammar(tokens: list[dict], builtins: list[dict], stdlib: list[dict]) -> dict:
    by_scope: dict[str, list[str]] = {}
    for entry in tokens:
        by_scope.setdefault(entry["scope"], []).extend(entry["forms"])

    patterns: list[dict] = [
        # Comments first, and line comments only: the lexer skips `//...` and
        # has no block comment at all, so a /* */ rule greyed out code the
        # compiler then rejected with a lex error.
        # An English comment that opens with `__` and has not closed yet.
        #
        # This rule comes first, and it is a block rule rather than a line
        # rule, because Rule 2's marks go at the ends of the *sentence*: `__`
        # on the first comment line and `__` on the last. The previous version
        # nested a single-line `__.+?__` inside the line-comment rule below,
        # so a sentence spanning two lines left each of them holding one
        # unmatched mark, neither matched, and the English in between was
        # coloured as ezuqqu. docs/reference/SCRIPT_RULES.md.
        #
        # `end` has two alternatives and the order matters. The closing mark
        # wins where there is one. Otherwise the region stops at the start of
        # a line that is not a comment — a zero-width lookahead, which ends
        # the rule without consuming anything — so one unclosed `__` cannot
        # colour the rest of the file English.
        {
            "name": "comment.line.double-slash.etamil",
            "contentName": "meta.english.comment.etamil",
            "begin": r"//[ 	]*__",
            "end": r"__|^(?=[ 	]*[^ 	/])",
            "beginCaptures": {"0": {"name": "punctuation.definition.comment.etamil"}},
        },
        {
            "name": "comment.line.double-slash.etamil",
            "begin": "//",
            "end": "$",
            "beginCaptures": {"0": {"name": "punctuation.definition.comment.etamil"}},
            # A marked run that does not start the comment — `// kaZakku
            # __two words__ mudivu`. Two such runs on one line are two, which
            # is why this stays non-greedy, and why the block rule above is
            # anchored to `//` and cannot swallow them.
            "patterns": [
                {
                    "name": "meta.english.comment.etamil",
                    "match": r"__.+?__",
                }
            ],
        },
        # Only double quotes. eTamil has no single-quoted string, and the old
        # grammar's `'...'` rule turned any stray apostrophe into a phantom
        # string that swallowed the rest of the file.
        {
            "name": "string.quoted.double.etamil",
            "begin": '"',
            "end": '"',
            "beginCaptures": {"0": {"name": "punctuation.definition.string.begin.etamil"}},
            "endCaptures": {"0": {"name": "punctuation.definition.string.end.etamil"}},
            "patterns": [
                # The five the lexer decodes.
                {"name": "constant.character.escape.etamil", "match": r'\\[ntr"\\]'},
                # Anything else keeps both characters rather than being an
                # escape, which is worth showing as different from the above.
                {"name": "invalid.illegal.unknown-escape.etamil", "match": r"\\."},
            ],
        },
        # Percentage before plain number, and no trailing \b: `%` is not a
        # word character, so `%\b` could never match before `;` or a newline
        # and every percentage literal fell through to the number rule.
        {
            "name": "constant.numeric.percentage.etamil",
            "match": r"\b\d+(?:\.\d+)?%",
        },
        {
            "name": "constant.numeric.decimal.etamil",
            # No digit separators: the lexer rejects 1_000, and highlighting
            # it as a number advertised a literal that does not exist.
            "match": r"\b\d+(?:\.\d+)?\b",
        },
        # `செயல் peyar(` — the definition, so the name reads as a definition
        # rather than as a call. The keyword is captured separately: a theme
        # colours keyword.*, not meta.*, so scoping the whole match as meta
        # would leave செயல் uncoloured in exactly the place it matters.
        {
            "name": "meta.function.declaration.etamil",
            "match": rf"({word_pattern(next(t['forms'] for t in tokens if t['token'] == 'Function'))})\s+({IDENT})",
            "captures": {
                "1": {"name": "keyword.declaration.function.etamil"},
                "2": {"name": "entity.name.function.etamil"},
            },
        },
        # A record key, before the keyword groups: `{வரி: 100}` produces the
        # field வரி, and a field name is data — what the author typed — not
        # the Tax keyword. Ordering this after the keyword patterns scoped it
        # as domain vocabulary instead.
        #
        # Safe ahead of the keywords because `:` appears nowhere else in the
        # grammar's reach: a quoted key and a path like "/kaNakku/:id" are
        # both already inside the string rule above.
        {
            "match": rf"({IDENT})\s*(:)",
            "captures": {
                "1": {"name": "variable.other.member.etamil"},
                "2": {"name": "punctuation.separator.key-value.etamil"},
            },
        },
    ]

    # Keyword groups. Ordered most specific first so a more precise scope
    # always wins at a given position.
    scope_order = [
        "keyword.control.conditional.etamil",
        "keyword.control.loop.etamil",
        "keyword.control.flow.return.etamil",
        "keyword.control.import.etamil",
        "keyword.control.route.etamil",
        "keyword.control.every.etamil",
        "keyword.control.etamil",
        "keyword.declaration.function.etamil",
        "keyword.operator.logical.etamil",
        "keyword.other.io.etamil",
        "keyword.other.response.etamil",
        "storage.type.etamil",
        "constant.language.boolean.etamil",
        "constant.language.null.etamil",
        "support.constant.http-method.etamil",
        "support.constant.database.etamil",
        "support.function.fileio.etamil",
        "support.function.database.etamil",
        "keyword.other.database.etamil",
        "keyword.other.sql.etamil",
        "keyword.other.http.etamil",
        "keyword.other.security.etamil",
        "keyword.other.etamil",
        "support.type.domain.etamil",
    ]
    missing = set(by_scope) - set(scope_order)
    if missing:
        die(f"scope(s) not placed in scope_order: {sorted(missing)}")

    for scope in scope_order:
        if scope in by_scope:
            patterns.append({"name": scope, "match": word_pattern(by_scope[scope])})

    # Functions the host provides, then the ones nUlakam defines. Both go
    # before the generic call rule so a known function keeps its own scope.
    patterns.append(
        {
            "name": "support.function.builtin.etamil",
            "match": word_pattern([f for b in builtins for f in b["forms"]]),
        }
    )
    patterns.append(
        {
            "name": "support.function.stdlib.etamil",
            "match": word_pattern([f["name"] for f in stdlib]),
        }
    )

    patterns.extend(
        [
            {
                "name": "entity.name.function.etamil",
                "match": rf"{IDENT}(?=\s*\()",
            },
            {
                "name": "variable.other.member.etamil",
                "match": rf"(?<=\.)\s*{IDENT}",
            },
            {"name": "keyword.operator.comparison.etamil", "match": r"==|!=|>=|<=|>|<"},
            {"name": "keyword.operator.assignment.etamil", "match": r"="},
            {"name": "keyword.operator.concat.etamil", "match": r"&"},
            {"name": "keyword.operator.arithmetic.etamil", "match": r"[+\-*/]"},
            # `?` — unwrap a சரி or hand the தவறு to the caller.
            {"name": "keyword.operator.try.etamil", "match": r"\?"},
            # A name marked English by Rule 1. Last of the name rules, so a
            # keyword (`_length`), a builtin and an nUlakam function keep the
            # scope that says what they are; what is left is the variables and
            # parameters people write.
            {
                "name": "variable.other.english.etamil",
                "match": rf"(?<![{TAMIL}\w])_[{TAMIL}\w]+",
            },
            {"name": "punctuation.accessor.etamil", "match": r"\."},
            {"name": "punctuation.terminator.etamil", "match": r";"},
            {"name": "punctuation.separator.etamil", "match": r","},
            {"name": "meta.brace.round.etamil", "match": r"[()]"},
            {"name": "meta.brace.square.etamil", "match": r"[\[\]]"},
            {"name": "meta.brace.curly.etamil", "match": r"[{}]"},
            {"name": "variable.other.etamil", "match": IDENT},
        ]
    )

    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "eTamil",
        "scopeName": "source.etamil",
        "fileTypes": ["qmz"],
        "_generated": BANNER,
        "patterns": patterns,
        "repository": {},
    }


# --------------------------------------------------------------------------
# TypeScript data
# --------------------------------------------------------------------------
def build_data(tokens: list[dict], builtins: list[dict], stdlib: list[dict]) -> str:
    keywords = []
    for entry in tokens:
        tamil_snippet, latin_snippet = SNIPPETS.get(entry["token"], (None, None))
        keywords.append(
            {
                "token": entry["token"],
                "forms": entry["forms"],
                "group": entry["section"],
                "scope": entry["scope"],
                "reserved": entry["reserved"],
                "noSyntax": entry["no_syntax"],
                "snippetTamil": tamil_snippet,
                "snippetLatin": latin_snippet,
            }
        )

    functions = [
        {
            "name": b["name"],
            "forms": b["forms"],
            "params": None,
            "arity": b["arity"],
            "doc": b["doc"],
            "kind": "builtin",
            "module": None,
            "line": None,
        }
        for b in builtins
    ] + [
        {
            "name": f["name"],
            "forms": f["forms"],
            "params": f["params"],
            "arity": len(f["params"]),
            "doc": f["doc"],
            "kind": "stdlib",
            "module": f["module"],
            "line": f["line"],
        }
        for f in stdlib
    ]

    def dump(value) -> str:
        return json.dumps(value, ensure_ascii=False, indent=2)

    return f"""// {BANNER}
//
// Sources: etamil_compiler/src/lexer.rs (keywords and every spelling),
// src/parser.rs (whether a word is reserved), src/vm/interpreter.rs
// (builtins), nUlakam/**/*.qmz (standard library).
//
// Regenerate with:  python scripts/generate_editor_support.py

/** One keyword, with every spelling the lexer accepts for it. */
export interface KeywordEntry {{
  /** The compiler's internal token name. */
  token: string;
  /** Tamil script first, then romanized, then any English alias. */
  forms: string[];
  /** The lexer section this keyword belongs to. */
  group: string;
  /** TextMate scope, matching the generated grammar. */
  scope: string;
  /** False when the parser accepts this word as an ordinary name. */
  reserved: boolean;
  /** Reserved, but no statement consumes it — using it is always an error. */
  noSyntax: boolean;
  /** Statement template for Tamil-script authors, or null. */
  snippetTamil: string | null;
  /** The same template with romanized placeholders, or null. */
  snippetLatin: string | null;
}}

/** A callable: a host builtin, or a செயல் defined in nUlakam. */
export interface FunctionEntry {{
  name: string;
  forms: string[];
  /** Parameter names, for stdlib functions whose source we can read. */
  params: string[] | null;
  /** Expected argument count, where it is known. */
  arity: number | null;
  doc: string;
  kind: 'builtin' | 'stdlib';
  /** Repository-relative path, for stdlib functions. */
  module: string | null;
  /** 1-based line of the செயல் that defines it, for Go to Definition. */
  line: number | null;
}}

export const KEYWORDS: readonly KeywordEntry[] = {dump(keywords)};

export const FUNCTIONS: readonly FunctionEntry[] = {dump(functions)};

/** Regex source matching one identifier, mirroring the lexer's own rule. */
export const IDENTIFIER_SOURCE = {json.dumps(IDENT)};
"""


# --------------------------------------------------------------------------

# --------------------------------------------------------------------------
# Pygments word lists
# --------------------------------------------------------------------------
#
# The lexer module itself is hand-written; only the word lists are generated,
# the way Pygments does it for other languages in `_*_builtins.py`. That keeps
# the regexes in one reviewable file and the vocabulary in step with the
# compiler.
#
# The groups are named for what the words are, not for a Pygments token, so
# that the mapping stays a decision the lexer makes in one visible place.

# TextMate scope -> word-list group.
PYG_GROUPS = {
    "keyword.control.conditional.etamil": "CONTROL",
    "keyword.control.loop.etamil": "CONTROL",
    "keyword.control.flow.return.etamil": "CONTROL",
    "keyword.control.route.etamil": "CONTROL",
    "keyword.control.every.etamil": "CONTROL",
    "keyword.control.import.etamil": "IMPORT",
    "keyword.declaration.function.etamil": "DECLARE_FUNCTION",
    "keyword.operator.logical.etamil": "LOGICAL",
    "keyword.other.io.etamil": "RESERVED",
    "keyword.other.response.etamil": "RESERVED",
    "keyword.other.http.etamil": "RESERVED",
    "keyword.other.sql.etamil": "RESERVED",
    "keyword.other.database.etamil": "RESERVED",
    "keyword.other.security.etamil": "RESERVED",
    "keyword.other.etamil": "RESERVED",
    "storage.type.etamil": "TYPE",
    "constant.language.boolean.etamil": "CONSTANT",
    "constant.language.null.etamil": "CONSTANT",
    "support.constant.http-method.etamil": "NAMED_CONSTANT",
    "support.constant.database.etamil": "NAMED_CONSTANT",
    "support.function.fileio.etamil": "BUILTIN",
    "support.function.database.etamil": "BUILTIN",
    "support.type.domain.etamil": "DOMAIN",
}

# Emission order, and the order the lexer must try them in. A form that lands
# in two groups belongs to the first one here: DOMAIN is last because it is the
# largest and the least specific.
PYG_ORDER = [
    "DECLARE_FUNCTION",
    "IMPORT",
    "CONTROL",
    "TYPE",
    "CONSTANT",
    "RESERVED",
    "LOGICAL",
    "NAMED_CONSTANT",
    "BUILTIN",
    "DOMAIN",
]


def build_pygments_words(
    tokens: list[dict], builtins: list[dict], stdlib: list[dict]
) -> str:
    """Emit the Pygments word lists from the shared grouping."""
    groups = pygments_groups(tokens, builtins, stdlib)

    lines = [
        '"""',
        "    Word lists for the eTamil lexer.",
        "",
        f"    {BANNER}",
        "",
        "    :copyright: Copyright 2026 Mohammed Maruff (Esan Maruff).",
        "    :license: BSD, see LICENSE for details.",
        '"""',
        "",
    ]
    for name in PYG_ORDER:
        lines.append(f"{name} = (")
        for form in groups[name]:
            lines.append(f"    {form!r},")
        lines.append(")")
        lines.append("")
    return "\n".join(lines)


def pygments_groups(
    tokens: list[dict], builtins: list[dict], stdlib: list[dict]
) -> dict[str, list[str]]:
    """The word lists, grouped and de-duplicated, shared by every highlighter.

    Pygments, Rouge and highlight.js all need the same question answered — which
    words are control flow, which are types, which are builtins — so they answer
    it from one place. Three hand-kept keyword lists would drift from each other
    and from the compiler, which is the failure this whole generator exists to
    prevent.
    """
    groups: dict[str, set[str]] = {name: set() for name in PYG_ORDER}

    for token in tokens:
        if token["no_syntax"]:
            continue
        group = PYG_GROUPS.get(token["scope"])
        if group is None:
            die(f"no highlighter group for scope {token['scope']}")
        groups[group].update(token["forms"])

    for entry in builtins:
        groups["BUILTIN"].update(entry["forms"])
    for entry in stdlib:
        groups["BUILTIN"].update(entry["forms"])

    # One form, one group. Earlier in PYG_ORDER wins.
    claimed: set[str] = set()
    ordered: dict[str, list[str]] = {}
    for name in PYG_ORDER:
        groups[name] -= claimed
        claimed |= groups[name]
        # Longest first: a prefix must never shadow the longer word it starts,
        # and none of these three engines sorts alternations for you.
        ordered[name] = sorted(groups[name], key=lambda form: (-len(form), form))
    return ordered


IDENT_TAIL = "[a-zA-Z0-9_\\u0B80-\\u0BFF]"
IDENT_RE = "[a-zA-Z_\\u0B80-\\u0BFF][a-zA-Z0-9_\\u0B80-\\u0BFF]*"


def build_rouge(groups: dict[str, list[str]]) -> str:
    """A Rouge lexer — what Jekyll and GitHub Pages highlight with.

    Written by substitution rather than as an f-string: the template is Ruby
    and regex, both full of braces and dollar signs, and an f-string would
    fight every one of them.

    The important detail is the word boundary. Rouge's `\\b` is ASCII-only, so
    a Tamil keyword anchored with it would never match; the guard here is an
    explicit "not followed by another identifier character", built from the
    same class the compiler's own lexer uses.
    """

    def words(names: list[str]) -> str:
        if not names:
            return "%r//"
        joined = "|".join(re.escape(name) for name in names)
        return "%r/(?:" + joined + ")(?!" + IDENT_TAIL + ")/"

    template = '''# -*- coding: utf-8 -*- #
# frozen_string_literal: true
#
# @@BANNER@@
#
# Rouge is what Jekyll and GitHub Pages highlight with, so this is the lexer
# that renders eTamil on https://etamil.in itself.
#
# Every keyword has interchangeable spellings — Tamil script, a romanized form
# typable on an unmodified keyboard, and for some an English alias. All of them
# come from the compiler's own token table, so this file cannot describe a
# language the compiler does not accept.

module Rouge
  module Lexers
    class ETamil < RegexLexer
      title 'eTamil'
      desc 'A Tamil-vocabulary language for Indian accounting, tax and FinTech (etamil.in)'
      tag 'etamil'
      aliases 'etamil'
      filenames '*.qmz', '*.etamil'
      mimetypes 'text/x-etamil'

      state :root do
        # Line comments only: the compiler's lexer has no block comment, so a
        # /* */ rule would grey out code that then fails to lex.
        rule %r(//.*$), Comment::Single

        rule %r/"/, Str::Double, :string

        # A percentage literal is exact — 18% is 0.18, not a rounded double —
        # which is worth showing as its own kind of number in a language for
        # tax arithmetic.
        rule %r/\\d+(?:\\.\\d+)?%/, Num::Other
        rule %r/\\d+\\.\\d+/, Num::Float
        rule %r/\\d+/, Num::Integer

        rule @@DECLARE_FUNCTION@@, Keyword::Declaration
        rule @@IMPORT@@, Keyword::Namespace
        rule @@CONTROL@@, Keyword
        rule @@TYPE@@, Keyword::Type
        rule @@CONSTANT@@, Keyword::Constant
        rule @@RESERVED@@, Keyword::Reserved
        rule @@LOGICAL@@, Operator::Word
        rule @@NAMED_CONSTANT@@, Name::Constant
        rule @@BUILTIN@@, Name::Builtin
        # Domain vocabulary — வரவு, பற்று, தொகை — is deliberately *not*
        # reserved: the parser accepts these as ordinary names, so colouring
        # them as syntax would tell the reader the opposite of the truth.
        rule @@DOMAIN@@, Name::Entity

        rule %r/@@IDENT@@/, Name

        rule %r/==|!=|>=|<=/, Operator
        rule %r/[+\\-*\\/&<>=?]/, Operator
        rule %r/[\\[\\](){}]/, Punctuation
        rule %r/[;,:.]/, Punctuation
        rule %r/\\s+/m, Text
      end

      state :string do
        rule %r/"/, Str::Double, :pop!
        # The five escapes the compiler decodes. An unrecognised escape keeps
        # both characters rather than being one, so it is shown as an error
        # instead of silently accepted.
        rule %r/\\\\[ntr"\\\\]/, Str::Escape
        rule %r/\\\\./, Error
        rule %r/[^"\\\\]+/m, Str::Double
      end
    end
  end
end
'''

    out = template.replace("@@BANNER@@", BANNER).replace("@@IDENT@@", IDENT_RE)
    for name in PYG_ORDER:
        out = out.replace("@@" + name + "@@", words(groups[name]))
    return out


def build_highlightjs(groups: dict[str, list[str]]) -> str:
    """A highlight.js definition, for web documentation and the playground.

    Neither Pygments nor Rouge runs in a browser, so the online manual and the
    wasm playground need this one.
    """

    def js_list(names: list[str]) -> str:
        return json.dumps(names, ensure_ascii=False)

    def alternation(names: list[str]) -> str:
        if not names:
            return "(?!)"
        return "(?:" + "|".join(re.escape(name) for name in names) + ")"

    template = '''/*
Language: eTamil
Description: A Tamil-vocabulary programming language for Indian accounting, tax and FinTech
Website: https://etamil.in
Category: common

@@BANNER@@
*/

/** @type LanguageFn */
export default function etamil(hljs) {
  // highlight.js decides what a "word" is with $pattern, and its default is
  // ASCII. Without this every Tamil keyword is invisible to the matcher, so
  // the pattern below is the whole reason the language highlights at all.
  const IDENT = /@@IDENT@@/;

  const KEYWORDS = {
    $pattern: IDENT,
    keyword: @@KEYWORDS@@,
    type: @@TYPE@@,
    literal: @@CONSTANT@@,
    built_in: @@BUILTINS@@,
  };

  const STRING = {
    className: 'string',
    begin: '"',
    end: '"',
    illegal: '\\n',
    contains: [
      // The five escapes the compiler decodes.
      { className: 'subst', begin: /\\\\[ntr"\\\\]/ },
    ],
  };

  const NUMBER = {
    className: 'number',
    variants: [
      // A percentage literal is exact: 18% is 0.18.
      { begin: /\\b\\d+(?:\\.\\d+)?%/ },
      { begin: /\\b\\d+\\.\\d+/ },
      { begin: /\\b\\d+/ },
    ],
    relevance: 0,
  };

  const DOMAIN = {
    // Domain vocabulary — வரவு, பற்று, தொகை — is deliberately not reserved:
    // the parser accepts these as ordinary names. Marked as a title rather
    // than a keyword so it reads as vocabulary, not syntax.
    className: 'title.class',
    begin: /@@DOMAIN@@(?!@@IDENT_TAIL@@)/,
    relevance: 0,
  };

  return {
    name: 'eTamil',
    aliases: ['etamil', 'qmz'],
    keywords: KEYWORDS,
    contains: [
      // Line comments only; the language has no block comment.
      hljs.COMMENT('//', '$'),
      STRING,
      NUMBER,
      DOMAIN,
    ],
  };
}
'''

    keywords = (
        groups["CONTROL"]
        + groups["DECLARE_FUNCTION"]
        + groups["IMPORT"]
        + groups["RESERVED"]
        + groups["LOGICAL"]
    )
    builtins = groups["BUILTIN"] + groups["NAMED_CONSTANT"]

    return (
        template.replace("@@BANNER@@", BANNER)
        .replace("@@IDENT_TAIL@@", IDENT_TAIL)
        .replace("@@IDENT@@", IDENT_RE)
        .replace("@@KEYWORDS@@", js_list(keywords))
        .replace("@@TYPE@@", js_list(groups["TYPE"]))
        .replace("@@CONSTANT@@", js_list(groups["CONSTANT"]))
        .replace("@@BUILTINS@@", js_list(builtins))
        .replace("@@DOMAIN@@", alternation(groups["DOMAIN"]))
    )


def build_treesitter_keywords(tokens: list[dict]) -> str:
    """Every spelling of every keyword, for grammar.js to build rules from.

    Only the vocabulary. `grammar.js` is written by hand because the shape of
    a statement — that eTamil puts the condition *before* the keyword, that a
    route takes a method and a literal path — is not recoverable from a list
    of tokens. Keeping the two apart is the same split as the snippet
    templates: generate what is derivable, hand-write what is not, and let CI
    fail if the derivable half drifts.
    """
    by_token: dict[str, list[str]] = {}
    for token in tokens:
        # Longest first so a prefix never shadows the longer word it starts.
        by_token[token["token"]] = sorted(
            token["forms"], key=lambda form: (-len(form), form)
        )

    lines = [
        "// " + BANNER,
        "//",
        "// Every spelling the compiler accepts for each keyword, keyed by the",
        "// token name in etamil_compiler/src/lexer.rs. grammar.js turns these",
        "// into `choice(...)` rules, so the grammar cannot parse a spelling",
        "// the compiler rejects, or miss one it accepts.",
        "",
        "module.exports = {",
    ]
    for name in sorted(by_token):
        forms = ", ".join(json.dumps(form, ensure_ascii=False) for form in by_token[name])
        lines.append(f"  {name}: [{forms}],")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


TREESITTER_GRAMMAR = ROOT / "tree-sitter-etamil" / "grammar.js"
TREESITTER_QUERIES = ROOT / "tree-sitter-etamil" / "queries" / "highlights.scm"


def build_treesitter_queries(tokens: list[dict], builtins: list[dict], stdlib: list[dict]) -> str:
    """Highlight queries for Neovim, Helix and Zed.

    Only the keywords `grammar.js` actually references can appear here. A
    tree-sitter query naming a string the parser has no rule for is a hard
    error — "Invalid node type" — and the language then fails to highlight at
    all rather than highlighting partially. Many of the lexer's tokens are
    reserved words that no statement consumes, so emitting every spelling
    produced exactly that.

    The set is read from `grammar.js` rather than kept by hand, so adding a
    keyword to a rule is enough to have it highlighted.
    """
    if not TREESITTER_GRAMMAR.exists():
        die(f"{TREESITTER_GRAMMAR} is missing")

    used = set(re.findall(r"kw\('(\w+)'\)", TREESITTER_GRAMMAR.read_text(encoding="utf-8")))
    if not used:
        die("grammar.js references no keywords; the kw('X') scan found nothing")

    groups = pygments_groups(tokens, builtins, stdlib)
    by_token = {token["token"]: token for token in tokens}

    # Which group each *used* token belongs to, so the query and the other
    # highlighters agree about what is control flow and what is a type.
    forms_for: dict[str, list[str]] = {name: [] for name in PYG_ORDER}
    for name in used:
        token = by_token.get(name)
        if token is None:
            die(f"grammar.js references kw('{name}'), which is not a lexer token")
        group = PYG_GROUPS.get(token["scope"])
        if group is None:
            die(f"no highlighter group for scope {token['scope']}")
        forms_for[group].extend(token["forms"])

    # Builtins and library functions are ordinary identifiers to the grammar,
    # so they are matched by predicate on (identifier) rather than as node
    # types. A #any-of? over 300 names is what tree-sitter is built for.
    builtin_names = sorted(
        {form for entry in builtins for form in entry["forms"]}
        | {entry["name"] for entry in stdlib}
    )

    def node_list(names: list[str]) -> str:
        unique = sorted(set(names), key=lambda form: (-len(form), form))
        return " ".join(json.dumps(form, ensure_ascii=False) for form in unique)

    def any_of(names: list[str]) -> str:
        return " ".join(json.dumps(name, ensure_ascii=False) for name in names)

    sections = [
        f"""; Highlight queries for eTamil.
;
; {BANNER}
;
; Neovim, Helix and Zed read this file directly. Capture names follow the
; nvim-treesitter convention, so eTamil picks up whatever colour scheme the
; reader already uses.
;
; Only keywords `grammar.js` actually references appear below. A query naming a
; string the parser has no rule for is a hard error, and the language then
; fails to highlight at all rather than partially.

; --- Comments and literals -------------------------------------------------

(comment) @comment @spell

(string) @string
(escape_sequence) @string.escape
; An unrecognised escape keeps both characters rather than being one, so it is
; shown as an error rather than silently accepted.
(invalid_escape) @error

(number) @number
; A percentage literal is exact — 18% is 0.18, never a rounded double — which
; is the whole point of a language for tax arithmetic.
(percentage) @number.float

(boolean) @boolean
(null) @constant.builtin

; --- Structure -------------------------------------------------------------

(function_definition name: (identifier) @function)
(parameter name: (identifier) @variable.parameter)
(call function: (identifier) @function.call)

(type) @type
(function_type) @type
(http_method) @constant.builtin

; நிலை and வடிவம் are keywords only where they bind a name or begin a shape,
; which is where the grammar names them `keyword`; anywhere else they are the
; ordinary names two examples and nUlakam use them as. `நிலை x = …` has the
; same form as `கடன் க = …`, so there it is told apart by its spelling.
(shape_definition keyword: (identifier) @keyword)
(fixed_declaration keyword: (identifier) @keyword)
(parameter modifier: (identifier) @keyword)
((typed_declaration type: (identifier) @keyword)
  (#any-of? @keyword "நிலை" "nilY" "_const"))
(shape_definition name: (identifier) @type)
(typed_declaration type: (identifier) @type)
(fixed_declaration type: (identifier) @type)
(parameter type: (identifier) @type)
(shape_field type: (identifier) @type)
(shape_literal shape: (identifier) @type)
(shape_field name: (identifier) @property)

; A field name is data — what the author typed — not a language construct, so
; the key in {{வரி: 1}} is a property and not the Tax keyword.
(pair key: (identifier) @property)
(pair key: (string) @property)
(field_access field: (identifier) @property)
(field_assignment field: (identifier) @property)

; --- Operators and punctuation ---------------------------------------------

[
  "+" "-" "*" "/" "&"
  "==" "!=" "<" "<=" ">" ">="
  "=" "?"
] @operator

[ "(" ")" "[" "]" "{{" "}}" ] @punctuation.bracket
[ ";" "," ":" "." ] @punctuation.delimiter
"""
    ]

    captures = [
        ("CONTROL", "@keyword"),
        ("DECLARE_FUNCTION", "@keyword.function"),
        ("IMPORT", "@keyword.import"),
        ("LOGICAL", "@keyword.operator"),
        ("RESERVED", "@keyword"),
        ("NAMED_CONSTANT", "@constant.builtin"),
        ("BUILTIN", "@function.builtin"),
        ("DOMAIN", "@variable.member"),
    ]

    sections.append(
        "\n; --- Keywords --------------------------------------------------------------\n;\n"
        "; Every spelling the compiler accepts for these: Tamil script, the romanized\n"
        "; form, and where one exists an English alias.\n"
    )
    for group, capture in captures:
        forms = forms_for[group]
        if not forms:
            continue
        if group == "DOMAIN":
            sections.append(
                "\n; Domain vocabulary — வரவு, பற்று, தொகை. Deliberately not @keyword: the\n"
                "; parser accepts these as ordinary names, and colouring them as syntax\n"
                "; would tell the reader the opposite of the truth.\n"
            )
        sections.append(f"[ {node_list(forms)} ] {capture}\n")

    # Identifiers last, so a more specific capture above always wins, with the
    # library matched by predicate.
    sections.append(
        f"""
; --- Names -----------------------------------------------------------------

; Host builtins and the nUlakam standard library are ordinary identifiers to
; the grammar, so they are matched by name rather than as node types.
((identifier) @function.builtin
  (#any-of? @function.builtin {any_of(builtin_names)}))

(identifier) @variable
"""
    )

    return "".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail if the committed files differ",
    )
    args = parser.parse_args()

    tokens = classify(read_tokens())
    builtins = read_builtins()
    stdlib = read_stdlib()

    grammar = json.dumps(
        build_grammar(tokens, builtins, stdlib), ensure_ascii=False, indent=2
    ) + "\n"
    data = build_data(tokens, builtins, stdlib)

    pygments_words = build_pygments_words(tokens, builtins, stdlib)
    groups = pygments_groups(tokens, builtins, stdlib)
    rouge = build_rouge(groups)
    treesitter = build_treesitter_keywords(tokens)
    ts_queries = build_treesitter_queries(tokens, builtins, stdlib)
    highlightjs = build_highlightjs(groups)

    outputs = [
        (GRAMMAR_OUT, grammar),
        (DATA_OUT, data),
        (PYGMENTS_OUT, pygments_words),
        (ROUGE_OUT, rouge),
        (HIGHLIGHTJS_OUT, highlightjs),
        (TREESITTER_OUT, treesitter),
        (TREESITTER_QUERIES, ts_queries),
    ]

    if args.check:
        stale = []
        for path, expected in outputs:
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != expected:
                stale.append(path.relative_to(ROOT).as_posix())
        if stale:
            print(
                "editor support is out of date with the compiler:\n  "
                + "\n  ".join(stale)
                + "\n\nrun: python scripts/generate_editor_support.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"editor support is current: {len(tokens)} keywords, "
            f"{len(builtins)} builtins, {len(stdlib)} stdlib functions"
        )
        return 0

    for path, contents in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8", newline="\n")

    reserved = sum(1 for t in tokens if t["reserved"])
    print(f"wrote {GRAMMAR_OUT.relative_to(ROOT).as_posix()}")
    print(f"wrote {DATA_OUT.relative_to(ROOT).as_posix()}")
    print(f"wrote {PYGMENTS_OUT.relative_to(ROOT).as_posix()}")
    print(f"wrote {ROUGE_OUT.relative_to(ROOT).as_posix()}")
    print(f"wrote {HIGHLIGHTJS_OUT.relative_to(ROOT).as_posix()}")
    print(f"wrote {TREESITTER_OUT.relative_to(ROOT).as_posix()}")
    print(f"wrote {TREESITTER_QUERIES.relative_to(ROOT).as_posix()}")
    print(
        f"  {len(tokens)} keywords ({reserved} reserved, "
        f"{len(tokens) - reserved} usable as names), "
        f"{len(builtins)} builtins, {len(stdlib)} stdlib functions"
    )
    without_snippet = [
        t["token"]
        for t in tokens
        if t["reserved"]
        and not t["no_syntax"]
        and t["token"] not in SNIPPETS
        and t["token"] not in NOT_A_STATEMENT
    ]
    if without_snippet:
        print(f"  no statement template yet: {', '.join(sorted(without_snippet))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
