#!/usr/bin/env python3
"""Regenerate docs/reference/KEYWORDS.md from the lexer's token table.

Run from the repository root after changing the token list:

    python scripts/generate_keywords.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEXER = ROOT / "etamil_compiler" / "src" / "lexer.rs"
OUT = ROOT / "docs" / "reference" / "KEYWORDS.md"

OPERATORS = {
    "=": "assignment", "+": "add", "-": "subtract (also unary minus)",
    "*": "multiply", "/": "divide", "&": "string concatenation",
    ">": "greater than", "<": "less than", "==": "equal", "!=": "not equal",
    ">=": "greater or equal", "<=": "less or equal",
    "(": "open group", ")": "close group", "{": "open block", "}": "close block",
    ",": "separator", ";": "end of statement",
}

HEADER = """# eTamil Keyword Reference

Every keyword in the language, grouped as the lexer groups them.

Each row lists the forms that produce the same token: Tamil script, the
romanized (ezuqqu) spelling, and where one exists an English alias. All
forms are interchangeable in source code.

The three Tamil nasals stay distinct in romanized form: **ண = `N`, ந = `n`,
ன = `Z`**.

> Generated by `scripts/generate_keywords.py` from `etamil_compiler/src/lexer.rs`.
> Do not edit by hand — rerun the script after changing the token list.
"""


def main() -> None:
    lines = LEXER.read_text(encoding="utf-8").splitlines()
    out = [HEADER]
    count = 0

    for line in lines:
        section = re.match(r"^\s*//\s*---\s*(.+?)\s*---", line)
        if section:
            title = re.sub(r"\s*\(.*?\)\s*$", "", section.group(1))
            out.append(f"\n## {title}\n")
            out.append("| Tamil | Romanized | English alias |")
            out.append("|---|---|---|")
            continue

        keyword = re.search(r'#\[regex\("([^"]+)"\)\]\s*(\w+)', line)
        if keyword:
            alts = keyword.group(1).split("|")
            tamil = alts[0]
            roman = f"`{alts[1]}`" if len(alts) > 1 else "—"
            english = f"`{alts[2]}`" if len(alts) > 2 else "—"
            out.append(f"| {tamil} | {roman} | {english} |")
            count += 1

    out.append("\n## Operators\n")
    out.append("| Symbol | Meaning |")
    out.append("|---|---|")
    for line in lines:
        token = re.search(r'#\[token\("([^"]+)"\)\]', line)
        if token:
            symbol = token.group(1)
            out.append(f"| `{symbol}` | {OPERATORS.get(symbol, '')} |")

    out.append("\n## Literals\n")
    out.append("| Form | Example | Notes |")
    out.append("|---|---|---|")
    out.append("| Number | `1500`, `99.99` | IEEE-754 `f64` |")
    out.append("| Percentage | `20%` | converted at lex time to `0.2` |")
    out.append('| String | `"vaNakkam"` | escape sequences are not yet unescaped |')
    out.append("| Identifier | `varuvAy`, `வருவாய்` | Tamil letters, ASCII letters, digits, underscore |")

    OUT.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} with {count} keyword rows")


if __name__ == "__main__":
    main()
