#!/usr/bin/env python3
"""Regenerate the VS Code extension's language data from the compiler itself.

The extension used to carry a hand-written keyword list. It drifted: by the
time anyone checked, 67 of the lexer's 201 keywords were missing from the
grammar and 28 romanized spellings were the pre-`Z` scheme, so the spellings
the editor highlighted were exactly the ones the compiler rejected. Nothing
could have caught that, because nothing derived one from the other.

Now everything that can be derived is. Run from the repository root after
changing the token list, the builtins, or nUlakam:

    python scripts/generate_editor_support.py
    python scripts/generate_editor_support.py --check   # CI: fail on drift

Written outputs:

    eTamil_Code/syntaxes/etamil.tmLanguage.json   TextMate grammar
    eTamil_Code/src/generated/language-data.ts    completions, hover, symbols

Three things are read, and nothing is duplicated by hand:

  lexer.rs        every keyword and every spelling of it, grouped by the
                  section comments the lexer already uses.
  parser.rs       `is_identifier_like` and `is_type_token`, which decide
                  whether a word is reserved or is usable as a name. This is
                  the distinction the old grammar got backwards — it
                  highlighted மாறி and நிலை as declarations when both are
                  ordinary names to the parser.
  interpreter.rs  the builtin functions, with their arity and doc comment.
  nUlakam/*.qmz   the standard library's own செயல் definitions.

What is *not* derived is the shape of each statement — `(cond) எனில் { }`
cannot be inferred from a token name. Those templates live in SNIPPETS below
and are the one part of this file that must be kept true by hand; every one
of them is exercised by tests/test_snippets.py.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEXER = ROOT / "etamil_compiler" / "src" / "lexer.rs"
PARSER = ROOT / "etamil_compiler" / "src" / "parser.rs"
INTERPRETER = ROOT / "etamil_compiler" / "src" / "vm" / "interpreter.rs"
NULAKAM = ROOT / "nUlakam"

EXT = ROOT / "eTamil_Code"
GRAMMAR_OUT = EXT / "syntaxes" / "etamil.tmLanguage.json"
DATA_OUT = EXT / "src" / "generated" / "language-data.ts"

TAMIL = "஀-௿"
# The same identifier shape the lexer accepts, so the grammar cannot scope
# something the compiler would refuse to tokenize.
IDENT = f"[a-zA-Z_{TAMIL}][a-zA-Z0-9_{TAMIL}]*"

BANNER = "Generated by scripts/generate_editor_support.py — do not edit by hand."


# --------------------------------------------------------------------------
# Scope assignment
# --------------------------------------------------------------------------
#
# A reserved word gets a keyword scope; a word the parser accepts as a name
# gets `support.type.domain`, because that is what it is — domain vocabulary
# the author may reuse. README says so explicitly: "தொகை is a perfectly good
# name for an amount." Colouring those as reserved told the reader the
# opposite of the truth.

# Section comment in lexer.rs -> scope for the reserved words in it.
SECTION_SCOPES = {
    "Core Financial & Accounting": "support.type.domain.etamil",
    "Transactions & Documents": "support.type.domain.etamil",
    "Money Movement": "support.type.domain.etamil",
    "Income & Costs": "support.type.domain.etamil",
    "Accounts, Reporting & Audit": "support.type.domain.etamil",
    "Indian Taxation": "support.type.domain.etamil",
    "Variables & Data Types": "storage.type.etamil",
    "Control Flow": "keyword.control.etamil",
    "Functions": "keyword.declaration.function.etamil",
    "Iteration": "keyword.control.loop.etamil",
    "Modules": "keyword.control.import.etamil",
    "File I/O Operations": "support.function.fileio.etamil",
    "Database Connectivity Operations": "support.function.database.etamil",
    "Database Types": "support.constant.database.etamil",
    "Database Operations": "keyword.other.database.etamil",
    "Database Clauses & Keywords": "keyword.other.sql.etamil",
    "REST API & HTTP": "keyword.other.http.etamil",
    "Encryption & Security": "keyword.other.security.etamil",
    "Logical Operators": "keyword.operator.logical.etamil",
}

# Where the section is too coarse. Keyed by the lexer's token name.
TOKEN_SCOPES = {
    "If": "keyword.control.conditional.etamil",
    "Else": "keyword.control.conditional.etamil",
    "Loop": "keyword.control.loop.etamil",
    "Print": "keyword.other.io.etamil",
    "Input": "keyword.other.io.etamil",
    "Return": "keyword.control.flow.return.etamil",
    "True": "constant.language.boolean.etamil",
    "False": "constant.language.boolean.etamil",
    "Null": "constant.language.null.etamil",
    "HttpGet": "support.constant.http-method.etamil",
    "HttpPost": "support.constant.http-method.etamil",
    "HttpPut": "support.constant.http-method.etamil",
    "HttpDelete": "support.constant.http-method.etamil",
    "HttpPatch": "support.constant.http-method.etamil",
    "HttpOptions": "support.constant.http-method.etamil",
    "HttpHead": "support.constant.http-method.etamil",
    "Route": "keyword.control.route.etamil",
    "Every": "keyword.control.every.etamil",
    "Response": "keyword.other.response.etamil",
}

# Reserved words the parser recognizes but no statement consumes, so the only
# thing an author can get out of them is "expected a statement". They stay
# highlighted — they really are reserved, and pretending otherwise would be a
# different lie — but the extension's hover says so, which is why the flag is
# carried through to the generated data rather than being dropped here.
NO_SYNTAX = {
    "Database", "DBSearch", "Table", "Collection", "Row", "Column", "Key",
    "PrimaryKey", "ForeignKey", "Index", "AlterTable", "DropTable",
    "OrderBy", "GroupBy", "Join", "Left", "Right", "Inner", "Outer",
    "Distinct", "Limit", "Offset",
    "API", "Endpoint", "Request", "Header", "Body", "Param", "QueryParam",
    "PathParam", "URL", "Host", "Port", "Method", "StatusCode",
    "StatusMessage", "Auth", "BearerToken", "ContentType", "Serve",
    "Encrypt", "Decrypt", "Password", "EncryptionKey",
    "File", "CSV", "Read", "Write", "Open", "Close", "FileLines",
    "SQL", "NoSQL", "MongoDB", "Redis", "JSONdb",
    "Let", "Const",
    "JSONBody",
}

# Statement shapes. Two templates per entry so a romanized author gets
# romanized placeholders: half of "Tamil semantics you can type on a plain
# keyboard" is the romanized path, and the old extension only served Tamil.
# `{kw}` is replaced with the spelling the author actually typed.
SNIPPETS = {
    "If": (
        "(${1:நிபந்தனை}) {kw} {\n\t$0\n}",
        "(${1:condition}) {kw} {\n\t$0\n}",
    ),
    "Else": ("{kw} {\n\t$0\n}", "{kw} {\n\t$0\n}"),
    "Loop": (
        "(${1:எண்ணி} < ${2:10}) {kw} {\n\t$0\n}",
        "(${1:i} < ${2:10}) {kw} {\n\t$0\n}",
    ),
    "Print": ("{kw} ${1:மதிப்பு};", "{kw} ${1:value};"),
    "Input": ("{kw} ${1:மாறி};", "{kw} ${1:name};"),
    "Function": (
        "{kw} ${1:பெயர்}(${2:அளவுரு}) {\n\t$0\n}",
        "{kw} ${1:name}(${2:param}) {\n\t$0\n}",
    ),
    "Return": ("{kw} ${1:மதிப்பு};", "{kw} ${1:value};"),
    "ForEach": (
        "{kw} ${1:உறுப்பு} இல் ${2:வரிசை} {\n\t$0\n}",
        "{kw} ${1:item} il ${2:items} {\n\t$0\n}",
    ),
    "Import": ('{kw} "${1:nUlakam/col.qmz}";', '{kw} "${1:nUlakam/col.qmz}";'),
    "IntegerType": ("{kw} ${1:பெயர்} = ${2:0};", "{kw} ${1:name} = ${2:0};"),
    "FloatType": ("{kw} ${1:பெயர்} = ${2:0.0};", "{kw} ${1:name} = ${2:0.0};"),
    "StringType": ('{kw} ${1:பெயர்} = "${2:உரை}";', '{kw} ${1:name} = "${2:text}";'),
    "TextType": ('{kw} ${1:பெயர்} = "${2:உரை}";', '{kw} ${1:name} = "${2:text}";'),
    # An array, record or boolean declaration must carry an initializer: a
    # bare `அணி x;` is rejected today, because the parser supplies 0 as the
    # implicit value and the checker holds that zero against the declared
    # type. Snippets that emitted the bare form produced a type error.
    "BoolType": ("{kw} ${1:பெயர்} = ${2:மெய்};", "{kw} ${1:name} = ${2:mey};"),
    "ArrayType": ("{kw} ${1:பெயர்} = [$2];", "{kw} ${1:name} = [$2];"),
    "ObjectType": (
        "{kw} ${1:பெயர்} = {${2:புலம்}: $3};",
        "{kw} ${1:name} = {${2:field}: $3};",
    ),
    "DataType": (
        "{kw} ${1:பெயர்} = {${2:புலம்}: $3};",
        "{kw} ${1:name} = {${2:field}: $3};",
    ),
    "DateType": ('{kw} ${1:பெயர்} = "${2:2026-04-01}";', '{kw} ${1:name} = "${2:2026-04-01}";'),
    "FileOpen": ('{kw} "${1:kOppu.txt}", "${2|read,write,append|}";', '{kw} "${1:file.txt}", "${2|read,write,append|}";'),
    "FileClose": ('{kw} "${1:kOppu.txt}";', '{kw} "${1:file.txt}";'),
    "FileWrite": ('{kw} "${1:kOppu.txt}", ${2:தரவு};', '{kw} "${1:file.txt}", ${2:data};'),
    "FileRead": ('{kw} "${1:kOppu.txt}", ${2:தரவு};', '{kw} "${1:file.txt}", ${2:data};'),
    "ReadCSV": ('{kw} "${1:qaravu.csv}", ${2:மொத்தம்};', '{kw} "${1:data.csv}", ${2:total};'),
    "WriteCSV": ('{kw} "${1:qaravu.csv}", ${2:நிரை};', '{kw} "${1:data.csv}", ${2:row};'),
    "DBConnect": ('{kw} ${1|சீகுலைட்,போச்குரசீகுல்,மைசீகுல்|}, "${2:kaNakku.db}";', '{kw} ${1|cIkulYt,pOckuracIkul,mYcIkul|}, "${2:kaNakku.db}";'),
    "DBDisconnect": ("{kw} ${1|சீகுலைட்,போச்குரசீகுல்,மைசீகுல்|};", "{kw} ${1|cIkulYt,pOckuracIkul,mYcIkul|};"),
    "DBQuery": (
        '{kw} "${1:SELECT * FROM pativukaL WHERE vakY = ?}", [${2:"வரவு"}], ${3:நிரைகள்};',
        '{kw} "${1:SELECT * FROM pativukaL WHERE vakY = ?}", [${2:"varavu"}], ${3:rows};',
    ),
    "DBExecute": (
        '{kw} "${1:INSERT INTO pativukaL(qokY) VALUES(?)}", [${2:1500}];',
        '{kw} "${1:INSERT INTO pativukaL(qokY) VALUES(?)}", [${2:1500}];',
    ),
    "Route": (
        '{kw} ${1|பெறு,பதி,இடு,அழி|}, "${2:/kaNakku/:id}" {\n\tபதில் 200, ${3:"ok"};\n}',
        '{kw} ${1|peRu,paqi,itu,azi|}, "${2:/kaNakku/:id}" {\n\tpaDil 200, ${3:"ok"};\n}',
    ),
    "Every": (
        '{kw} ${1:3600} {\n\t${2:அச்சு "ஒவ்வொரு மணிநேரமும்";}\n}',
        '{kw} ${1:3600} {\n\t${2:accu "every hour";}\n}',
    ),
    "Response": ('{kw} ${1:200}, ${2:"ok"};', '{kw} ${1:200}, ${2:"ok"};'),
    "StartServer": ('{kw} "${1:127.0.0.1}", ${2:8080};', '{kw} "${1:127.0.0.1}", ${2:8080};'),
    "Select": (
        "{kw} ${1:peyar} இதனில் ${2:pativukaL};",
        "{kw} ${1:peyar} iqaZil ${2:pativukaL};",
    ),
    # These four parse but the VM refuses them, so the template carries the
    # warning rather than leaving the author to discover it at run time.
    "CreateTable": (
        '{kw} ${1:pativukaL}, {${2:qokY}: "${3:TEXT}"};  // VM: not implemented — use தளம்_செய்',
        '{kw} ${1:pativukaL}, {${2:qokY}: "${3:TEXT}"};  // VM: not implemented — use qaLam_cey',
    ),
    "DBInsert": (
        '{kw} ${1:pativukaL}, {${2:qokY}: ${3:1500}};  // VM: not implemented — use தளம்_செய்',
        '{kw} ${1:pativukaL}, {${2:qokY}: ${3:1500}};  // VM: not implemented — use qaLam_cey',
    ),
    "DBUpdate": (
        '{kw} ${1:pativukaL}, {${2:qokY}: ${3:1500}};  // VM: not implemented — use தளம்_செய்',
        '{kw} ${1:pativukaL}, {${2:qokY}: ${3:1500}};  // VM: not implemented — use qaLam_cey',
    ),
    "DBDelete": (
        "{kw} ${1:pativukaL}, ${2:நிபந்தனை};  // VM: not implemented — use தளம்_செய்",
        "{kw} ${1:pativukaL}, ${2:condition};  // VM: not implemented — use qaLam_cey",
    ),
    "StopServer": ("{kw};", "{kw};"),
}

# Reserved words that are legitimately not statement-initial — clause words,
# operators, literals, and the names of methods and backends that appear as
# arguments inside another statement's template. Listing them keeps the
# generator's "no template yet" report meaningful.
NOT_A_STATEMENT = {
    "And", "Or", "Not",
    "True", "False", "Null",
    "In", "From", "Where",
    "HttpGet", "HttpPost", "HttpPut", "HttpDelete", "HttpPatch",
    "HttpOptions", "HttpHead",
    "SQLite", "MySQL", "PostgreSQL",
}


def die(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(2)


def is_tamil(text: str) -> bool:
    return any("஀" <= ch <= "௿" for ch in text)


# --------------------------------------------------------------------------
# Reading the compiler
# --------------------------------------------------------------------------
def read_tokens() -> list[dict]:
    """Every keyword in lexer.rs, in declaration order, tagged with section."""
    tokens: list[dict] = []
    section = ""
    for line in LEXER.read_text(encoding="utf-8").splitlines():
        heading = re.match(r"^\s*//\s*---\s*(.+?)\s*---", line)
        if heading:
            # "Control Flow (Your Updated Syntax)" -> "Control Flow"
            section = re.sub(r"\s*\(.*?\)\s*$", "", heading.group(1)).strip()
            continue
        entry = re.search(r'#\[regex\("([^"]+)"\)\]\s*(\w+)', line)
        if entry:
            tokens.append(
                {
                    "token": entry.group(2),
                    "forms": entry.group(1).split("|"),
                    "section": section,
                }
            )
    if not tokens:
        die(f"no keywords found in {LEXER}")
    return tokens


def read_parser_classification() -> tuple[set[str], set[str]]:
    """The parser's own answer to "may this word be a name?".

    Returns (not_a_name, type_keywords). Derived rather than restated: the
    grammar's job is to reflect the parser, and a second hand-kept copy of
    this list is what went wrong last time.
    """
    source = PARSER.read_text(encoding="utf-8")

    body = re.search(
        r"fn is_identifier_like\(token: &Token\) -> bool \{(.*?)\n    \}",
        source,
        re.S,
    )
    if not body:
        die("could not find is_identifier_like in parser.rs")
    # Every arm ending in `=> false` names words that cannot be identifiers.
    not_a_name: set[str] = set()
    for arm in re.findall(r"^(.*?)=>\s*false\s*,", body.group(1), re.M):
        not_a_name.update(re.findall(r"Token::(\w+)", arm))
    if not not_a_name:
        die("is_identifier_like matched no `=> false` arms")

    types = re.search(
        r"fn is_type_token\(token: &Token\) -> bool \{(.*?)\n    \}", source, re.S
    )
    if not types:
        die("could not find is_type_token in parser.rs")
    type_keywords = set(re.findall(r"Token::(\w+)", types.group(1)))

    return not_a_name, type_keywords


def read_builtins() -> list[dict]:
    """Host builtins from the interpreter's call_builtin match."""
    lines = INTERPRETER.read_text(encoding="utf-8").splitlines()
    builtins: list[dict] = []

    for index, line in enumerate(lines):
        arm = re.match(r'^\s+("(?:[^"]+)"(?:\s*\|\s*"[^"]+")+)\s*=>\s*\{', line)
        if not arm:
            continue
        forms = re.findall(r'"([^"]+)"', arm.group(1))
        if not is_tamil(forms[0]):
            continue  # a string match that is not a builtin name

        # The doc convention here is a comment block directly above the arm,
        # whose first useful line reads `// நீளம்(...) — what it does`.
        doc: list[str] = []
        cursor = index - 1
        while cursor >= 0:
            stripped = lines[cursor].strip()
            if not stripped.startswith("//"):
                break
            doc.append(stripped.lstrip("/").strip())
            cursor -= 1
        doc.reverse()

        # Arity, where the arm states it.
        arity = None
        for probe in lines[index : index + 6]:
            want = re.search(r"expect_args\(name,\s*&args,\s*(\d+)\)", probe)
            if want:
                arity = int(want.group(1))
                break

        builtins.append(
            {
                "name": forms[0],
                "forms": forms,
                "doc": pick_doc(doc, forms[0]),
                "arity": arity,
            }
        )

    if not builtins:
        die("no builtins found in interpreter.rs")
    return builtins


def pick_doc(doc_lines: list[str], name: str) -> str:
    """The line of a comment block that describes `name`, else the first."""
    for line in doc_lines:
        if line.startswith(name):
            return line
    for line in doc_lines:
        if line and not line.startswith("---"):
            return line
    return ""


def read_stdlib() -> list[dict]:
    """Every செயல் the standard library defines, with params and doc."""
    functions: list[dict] = []

    for path in sorted(NULAKAM.rglob("*.qmz")):
        module = path.relative_to(ROOT).as_posix()
        lines = path.read_text(encoding="utf-8").splitlines()

        for index, line in enumerate(lines):
            if not re.match(rf"^\s*(?:செயல்|ceyal|_fn)\s+{IDENT}\s*\(", line):
                continue
            # A long parameter list wraps. Join forward to the closing paren,
            # or the 14 widest functions in the accounting framework — the
            # ones most worth completing — go missing.
            header = line
            probe = index
            while ")" not in header and probe + 1 < len(lines):
                probe += 1
                header += " " + lines[probe].strip()
            define = re.match(
                rf"^\s*(?:செயல்|ceyal|_fn)\s+({IDENT})\s*\((.*?)\)", header
            )
            if not define:
                continue
            name = define.group(1)
            params = [p.strip() for p in define.group(2).split(",") if p.strip()]

            doc: list[str] = []
            cursor = index - 1
            while cursor >= 0:
                stripped = lines[cursor].strip()
                if not stripped.startswith("//"):
                    break
                doc.append(stripped.lstrip("/").strip())
                cursor -= 1
            doc.reverse()

            functions.append(
                {
                    "name": name,
                    "forms": [name],
                    "params": params,
                    "doc": pick_doc(doc, name),
                    "module": module,
                    # 1-based, so Go to Definition can open the library at the
                    # செயல் line rather than at the top of the file.
                    "line": index + 1,
                }
            )

    if not functions:
        die(f"no செயல் definitions found under {NULAKAM}")
    return functions


# --------------------------------------------------------------------------
# Classification
# --------------------------------------------------------------------------
def classify(tokens: list[dict]) -> list[dict]:
    not_a_name, type_keywords = read_parser_classification()

    for entry in tokens:
        token = entry["token"]
        # `take_name` accepts a token when it is identifier-like *and* not a
        # type keyword, so a type keyword is equally unusable as a name even
        # though is_identifier_like says nothing about it. Reporting only the
        # first half would tell an author that `சொல் உரை = "x";` is fine.
        entry["reserved"] = token in not_a_name or token in type_keywords
        entry["no_syntax"] = token in NO_SYNTAX

        if token in TOKEN_SCOPES:
            entry["scope"] = TOKEN_SCOPES[token]
        elif token in type_keywords:
            entry["scope"] = "storage.type.etamil"
        elif not entry["reserved"]:
            # Usable as a name, so not a keyword however domain-specific it
            # looks. `support.` reads as vocabulary, not syntax.
            entry["scope"] = "support.type.domain.etamil"
        else:
            entry["scope"] = SECTION_SCOPES.get(
                entry["section"], "keyword.other.etamil"
            )

    return tokens


# --------------------------------------------------------------------------
# Grammar
# --------------------------------------------------------------------------
def word_pattern(forms: list[str]) -> str:
    """A \\b-anchored alternation, longest first.

    Longest-first is not strictly required — the trailing \\b already forces
    the regex to backtrack from கோப்பு to கோப்பு_திற — but relying on that is
    a trap for whoever edits this next.
    """
    ordered = sorted(set(forms), key=lambda form: (-len(form), form))
    return r"\b(?:" + "|".join(re.escape(f) for f in ordered) + r")\b"


def build_grammar(tokens: list[dict], builtins: list[dict], stdlib: list[dict]) -> dict:
    by_scope: dict[str, list[str]] = {}
    for entry in tokens:
        by_scope.setdefault(entry["scope"], []).extend(entry["forms"])

    patterns: list[dict] = [
        # Comments first, and line comments only: the lexer skips `//...` and
        # has no block comment at all, so a /* */ rule greyed out code the
        # compiler then rejected with a lex error.
        {
            "name": "comment.line.double-slash.etamil",
            "begin": "//",
            "end": "$",
            "beginCaptures": {"0": {"name": "punctuation.definition.comment.etamil"}},
        },
        # Only double quotes. eTamil has no single-quoted string, and the old
        # grammar's `'...'` rule turned any stray apostrophe into a phantom
        # string that swallowed the rest of the file.
        {
            "name": "string.quoted.double.etamil",
            "begin": '"',
            "end": '"',
            "beginCaptures": {"0": {"name": "punctuation.definition.string.begin.etamil"}},
            "endCaptures": {"0": {"name": "punctuation.definition.string.end.etamil"}},
            "patterns": [
                # The five the lexer decodes.
                {"name": "constant.character.escape.etamil", "match": r'\\[ntr"\\]'},
                # Anything else keeps both characters rather than being an
                # escape, which is worth showing as different from the above.
                {"name": "invalid.illegal.unknown-escape.etamil", "match": r"\\."},
            ],
        },
        # Percentage before plain number, and no trailing \b: `%` is not a
        # word character, so `%\b` could never match before `;` or a newline
        # and every percentage literal fell through to the number rule.
        {
            "name": "constant.numeric.percentage.etamil",
            "match": r"\b\d+(?:\.\d+)?%",
        },
        {
            "name": "constant.numeric.decimal.etamil",
            # No digit separators: the lexer rejects 1_000, and highlighting
            # it as a number advertised a literal that does not exist.
            "match": r"\b\d+(?:\.\d+)?\b",
        },
        # `செயல் peyar(` — the definition, so the name reads as a definition
        # rather than as a call. The keyword is captured separately: a theme
        # colours keyword.*, not meta.*, so scoping the whole match as meta
        # would leave செயல் uncoloured in exactly the place it matters.
        {
            "name": "meta.function.declaration.etamil",
            "match": rf"({word_pattern(next(t['forms'] for t in tokens if t['token'] == 'Function'))})\s+({IDENT})",
            "captures": {
                "1": {"name": "keyword.declaration.function.etamil"},
                "2": {"name": "entity.name.function.etamil"},
            },
        },
        # A record key, before the keyword groups: `{வரி: 100}` produces the
        # field வரி, and a field name is data — what the author typed — not
        # the Tax keyword. Ordering this after the keyword patterns scoped it
        # as domain vocabulary instead.
        #
        # Safe ahead of the keywords because `:` appears nowhere else in the
        # grammar's reach: a quoted key and a path like "/kaNakku/:id" are
        # both already inside the string rule above.
        {
            "match": rf"({IDENT})\s*(:)",
            "captures": {
                "1": {"name": "variable.other.member.etamil"},
                "2": {"name": "punctuation.separator.key-value.etamil"},
            },
        },
    ]

    # Keyword groups. Ordered most specific first so a more precise scope
    # always wins at a given position.
    scope_order = [
        "keyword.control.conditional.etamil",
        "keyword.control.loop.etamil",
        "keyword.control.flow.return.etamil",
        "keyword.control.import.etamil",
        "keyword.control.route.etamil",
        "keyword.control.every.etamil",
        "keyword.control.etamil",
        "keyword.declaration.function.etamil",
        "keyword.operator.logical.etamil",
        "keyword.other.io.etamil",
        "keyword.other.response.etamil",
        "storage.type.etamil",
        "constant.language.boolean.etamil",
        "constant.language.null.etamil",
        "support.constant.http-method.etamil",
        "support.constant.database.etamil",
        "support.function.fileio.etamil",
        "support.function.database.etamil",
        "keyword.other.database.etamil",
        "keyword.other.sql.etamil",
        "keyword.other.http.etamil",
        "keyword.other.security.etamil",
        "keyword.other.etamil",
        "support.type.domain.etamil",
    ]
    missing = set(by_scope) - set(scope_order)
    if missing:
        die(f"scope(s) not placed in scope_order: {sorted(missing)}")

    for scope in scope_order:
        if scope in by_scope:
            patterns.append({"name": scope, "match": word_pattern(by_scope[scope])})

    # Functions the host provides, then the ones nUlakam defines. Both go
    # before the generic call rule so a known function keeps its own scope.
    patterns.append(
        {
            "name": "support.function.builtin.etamil",
            "match": word_pattern([f for b in builtins for f in b["forms"]]),
        }
    )
    patterns.append(
        {
            "name": "support.function.stdlib.etamil",
            "match": word_pattern([f["name"] for f in stdlib]),
        }
    )

    patterns.extend(
        [
            {
                "name": "entity.name.function.etamil",
                "match": rf"{IDENT}(?=\s*\()",
            },
            {
                "name": "variable.other.member.etamil",
                "match": rf"(?<=\.)\s*{IDENT}",
            },
            {"name": "keyword.operator.comparison.etamil", "match": r"==|!=|>=|<=|>|<"},
            {"name": "keyword.operator.assignment.etamil", "match": r"="},
            {"name": "keyword.operator.concat.etamil", "match": r"&"},
            {"name": "keyword.operator.arithmetic.etamil", "match": r"[+\-*/]"},
            # `?` — unwrap a சரி or hand the தவறு to the caller.
            {"name": "keyword.operator.try.etamil", "match": r"\?"},
            {"name": "punctuation.accessor.etamil", "match": r"\."},
            {"name": "punctuation.terminator.etamil", "match": r";"},
            {"name": "punctuation.separator.etamil", "match": r","},
            {"name": "meta.brace.round.etamil", "match": r"[()]"},
            {"name": "meta.brace.square.etamil", "match": r"[\[\]]"},
            {"name": "meta.brace.curly.etamil", "match": r"[{}]"},
            {"name": "variable.other.etamil", "match": IDENT},
        ]
    )

    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "eTamil",
        "scopeName": "source.etamil",
        "fileTypes": ["etamil", "qmz"],
        "_generated": BANNER,
        "patterns": patterns,
        "repository": {},
    }


# --------------------------------------------------------------------------
# TypeScript data
# --------------------------------------------------------------------------
def build_data(tokens: list[dict], builtins: list[dict], stdlib: list[dict]) -> str:
    keywords = []
    for entry in tokens:
        tamil_snippet, latin_snippet = SNIPPETS.get(entry["token"], (None, None))
        keywords.append(
            {
                "token": entry["token"],
                "forms": entry["forms"],
                "group": entry["section"],
                "scope": entry["scope"],
                "reserved": entry["reserved"],
                "noSyntax": entry["no_syntax"],
                "snippetTamil": tamil_snippet,
                "snippetLatin": latin_snippet,
            }
        )

    functions = [
        {
            "name": b["name"],
            "forms": b["forms"],
            "params": None,
            "arity": b["arity"],
            "doc": b["doc"],
            "kind": "builtin",
            "module": None,
            "line": None,
        }
        for b in builtins
    ] + [
        {
            "name": f["name"],
            "forms": f["forms"],
            "params": f["params"],
            "arity": len(f["params"]),
            "doc": f["doc"],
            "kind": "stdlib",
            "module": f["module"],
            "line": f["line"],
        }
        for f in stdlib
    ]

    def dump(value) -> str:
        return json.dumps(value, ensure_ascii=False, indent=2)

    return f"""// {BANNER}
//
// Sources: etamil_compiler/src/lexer.rs (keywords and every spelling),
// src/parser.rs (whether a word is reserved), src/vm/interpreter.rs
// (builtins), nUlakam/**/*.qmz (standard library).
//
// Regenerate with:  python scripts/generate_editor_support.py

/** One keyword, with every spelling the lexer accepts for it. */
export interface KeywordEntry {{
  /** The compiler's internal token name. */
  token: string;
  /** Tamil script first, then romanized, then any English alias. */
  forms: string[];
  /** The lexer section this keyword belongs to. */
  group: string;
  /** TextMate scope, matching the generated grammar. */
  scope: string;
  /** False when the parser accepts this word as an ordinary name. */
  reserved: boolean;
  /** Reserved, but no statement consumes it — using it is always an error. */
  noSyntax: boolean;
  /** Statement template for Tamil-script authors, or null. */
  snippetTamil: string | null;
  /** The same template with romanized placeholders, or null. */
  snippetLatin: string | null;
}}

/** A callable: a host builtin, or a செயல் defined in nUlakam. */
export interface FunctionEntry {{
  name: string;
  forms: string[];
  /** Parameter names, for stdlib functions whose source we can read. */
  params: string[] | null;
  /** Expected argument count, where it is known. */
  arity: number | null;
  doc: string;
  kind: 'builtin' | 'stdlib';
  /** Repository-relative path, for stdlib functions. */
  module: string | null;
  /** 1-based line of the செயல் that defines it, for Go to Definition. */
  line: number | null;
}}

export const KEYWORDS: readonly KeywordEntry[] = {dump(keywords)};

export const FUNCTIONS: readonly FunctionEntry[] = {dump(functions)};

/** Regex source matching one identifier, mirroring the lexer's own rule. */
export const IDENTIFIER_SOURCE = {json.dumps(IDENT)};
"""


# --------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail if the committed files differ",
    )
    args = parser.parse_args()

    tokens = classify(read_tokens())
    builtins = read_builtins()
    stdlib = read_stdlib()

    grammar = json.dumps(
        build_grammar(tokens, builtins, stdlib), ensure_ascii=False, indent=2
    ) + "\n"
    data = build_data(tokens, builtins, stdlib)

    outputs = [(GRAMMAR_OUT, grammar), (DATA_OUT, data)]

    if args.check:
        stale = []
        for path, expected in outputs:
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != expected:
                stale.append(path.relative_to(ROOT).as_posix())
        if stale:
            print(
                "editor support is out of date with the compiler:\n  "
                + "\n  ".join(stale)
                + "\n\nrun: python scripts/generate_editor_support.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"editor support is current: {len(tokens)} keywords, "
            f"{len(builtins)} builtins, {len(stdlib)} stdlib functions"
        )
        return 0

    for path, contents in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8", newline="\n")

    reserved = sum(1 for t in tokens if t["reserved"])
    print(f"wrote {GRAMMAR_OUT.relative_to(ROOT).as_posix()}")
    print(f"wrote {DATA_OUT.relative_to(ROOT).as_posix()}")
    print(
        f"  {len(tokens)} keywords ({reserved} reserved, "
        f"{len(tokens) - reserved} usable as names), "
        f"{len(builtins)} builtins, {len(stdlib)} stdlib functions"
    )
    without_snippet = [
        t["token"]
        for t in tokens
        if t["reserved"]
        and not t["no_syntax"]
        and t["token"] not in SNIPPETS
        and t["token"] not in NOT_A_STATEMENT
    ]
    if without_snippet:
        print(f"  no statement template yet: {', '.join(sorted(without_snippet))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
