// eTamil Virtual Machine (VM)
// Executes bytecode independently without LLVM or Rust compilation

// Where input and output go: std::fs and stdout natively, an in-memory
// buffer and file map in the browser. See host.rs.
pub mod bytecode;
pub mod host;
pub mod interpreter;
pub mod shape;
pub mod value;

pub use bytecode::{Bytecode, Instruction};
pub use interpreter::Upload;
pub use interpreter::VM;
pub use value::Value;

// Every builtin's names, generated by build.rs from the arms of
// VM::call_builtin, so the list cannot drift from the dispatch it describes.
mod builtin_names {
    include!(concat!(env!("OUT_DIR"), "/builtin_names.rs"));
}

/// Is this one of the builtins, under any of its spellings?
///
/// What lets `ச = நீளம்;` make a function value while a mistyped name is
/// still an undefined variable. Both backends ask this, so they agree on
/// which names are functions.
pub fn is_builtin(name: &str) -> bool {
    builtin_names::BUILTIN_NAMES.binary_search(&name).is_ok()
}

/// Initialize the eTamil VM with bytecode
pub fn create_vm() -> VM {
    VM::new()
}

/// Compile AST to bytecode (from parser module)
pub fn compile_to_bytecode(statements: Vec<crate::parser::Stmt>) -> Bytecode {
    bytecode::compiler::BytecodeCompiler::compile_statements(statements)
}

/// Execute bytecode directly
pub fn execute(bytecode: Bytecode) -> Result<(), String> {
    let mut vm = VM::new();
    vm.execute(bytecode)
}

// Re-export for convenience
pub use bytecode::compiler::BytecodeCompiler;
