// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Mohammed Maruff (Esan Maruff) <esan@etamil.in>
//! Compile `nUlakam/` — the standard library, itself written in eTamil — into
//! the binary.
//!
//! Why this exists: every filesystem lookup in `module::locate` needs someone
//! to have *placed* the library somewhere. The installers in `packaging/` do
//! that, and set `ETAMIL_PATH`. A package manager does not: `cargo install`,
//! `pip install`, `brew install` and a bare `winget` drop an executable on the
//! PATH and nothing else. Installed that way, with `ETAMIL_PATH` unset, the
//! compiler answered
//!
//!     ✗ தொகுதி 'nUlakam/paNam.qmz' கண்டுபிடிக்க முடியவில்லை
//!
//! to the first line of the README's own money example. A language whose
//! standard library disappears when it is installed the ordinary way cannot
//! honestly be listed as installable, so the library now travels inside the
//! executable and the filesystem lookups become an override rather than the
//! only route.
//!
//! Two layouts have to work:
//!
//!   * the repository, where the library is `../nUlakam` — one directory up,
//!     because it belongs to the *language*, not to this Rust crate; and
//!   * a published crate, where nothing above the package root is shipped, so
//!     `scripts/vendor_stdlib.py` copies it to `nUlakam/` here first. That copy
//!     is gitignored: it is generated at publish time and never committed, so
//!     it cannot drift from the original the way a second hand-kept copy would.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn main() {
    let root = match stdlib_root() {
        Some(root) => root,
        None => {
            // A hard error rather than an empty library. Silently building a
            // compiler with no standard library is the failure this file
            // exists to prevent, and it would only surface at the user's
            // first import.
            panic!(
                "cannot find the eTamil standard library.\n\
                 Looked for ../nUlakam (repository layout) and ./nUlakam \
                 (packaged layout).\n\
                 If you are packaging, run: python scripts/vendor_stdlib.py"
            );
        }
    };

    // Keyed the way an author writes the import — `nUlakam/paNam.qmz` — so the
    // embedded tree and the on-disk one are addressed identically.
    let prefix = root
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| "nUlakam".to_string());

    let mut modules: BTreeMap<String, PathBuf> = BTreeMap::new();
    collect(&root, &prefix, &mut modules);

    if modules.is_empty() {
        panic!("{} contains no .qmz files", root.display());
    }

    let mut out = String::new();
    out.push_str(
        "// Generated by build.rs from the eTamil standard library.\n\
         // Sorted by key so the table can be searched by bisection.\n\
         pub static EMBEDDED_STDLIB: &[(&str, &str)] = &[\n",
    );
    for (key, path) in &modules {
        // include_str! rather than embedding the text here: it keeps this
        // generated file small and lets rustc handle escaping of Tamil source.
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            key,
            path.to_string_lossy()
        ));
        println!("cargo:rerun-if-changed={}", path.display());
    }
    out.push_str("];\n");

    let destination = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_stdlib.rs");
    std::fs::write(&destination, out).expect("could not write the embedded standard library");

    println!("cargo:rerun-if-changed={}", root.display());
    println!("cargo:rerun-if-changed=build.rs");

    write_builtin_names();
}

/// Every builtin's names, read out of the interpreter's own dispatch.
///
/// `ச = நீளம்;` makes a function value of a builtin, and a mistyped name must
/// still be an undefined variable rather than a function value that fails only
/// when it is called. That needs the builtin names at the point a name is read,
/// and the one list that cannot drift is the `match` in `call_builtin` itself.
/// `scripts/generate_editor_support.py` reads the same arms the same way, for
/// the same reason: an arm whose first spelling is Tamil is a builtin, and every
/// spelling on it is one of its names.
fn write_builtin_names() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let interpreter = manifest.join("src").join("vm").join("interpreter.rs");
    let source =
        std::fs::read_to_string(&interpreter).expect("could not read src/vm/interpreter.rs");

    let mut names: Vec<String> = source.lines().filter_map(builtin_arm).flatten().collect();
    names.sort();
    names.dedup();
    if names.is_empty() {
        panic!("no builtins found in src/vm/interpreter.rs");
    }

    let mut out = String::from(
        "// Generated by build.rs from the arms of VM::call_builtin.\n\
         // Sorted so a name can be found by bisection.\n\
         pub static BUILTIN_NAMES: &[&str] = &[\n",
    );
    for name in &names {
        out.push_str(&format!("    {:?},\n", name));
    }
    out.push_str("];\n");

    let destination = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("builtin_names.rs");
    std::fs::write(&destination, out).expect("could not write the builtin names");
    println!("cargo:rerun-if-changed={}", interpreter.display());
}

/// The spellings on one `"a" | "b" | "c" => {` arm, if this line is a builtin's.
///
/// Two or more quoted forms joined by `|`, then `=> {`, and the first form in
/// Tamil: a string match anywhere else in the interpreter is not a builtin.
fn builtin_arm(line: &str) -> Option<Vec<String>> {
    let head = line
        .trim()
        .strip_suffix('{')?
        .trim_end()
        .strip_suffix("=>")?
        .trim_end();
    let mut forms = Vec::new();
    for part in head.split('|') {
        let inner = part.trim().strip_prefix('"')?.strip_suffix('"')?;
        if inner.is_empty() || inner.contains('"') {
            return None;
        }
        forms.push(inner.to_string());
    }
    let tamil = |c: char| ('\u{0B80}'..='\u{0BFF}').contains(&c);
    if forms.len() < 2 || !forms[0].chars().any(tamil) {
        return None;
    }
    Some(forms)
}

/// The standard library directory, in whichever layout is present.
fn stdlib_root() -> Option<PathBuf> {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").ok()?);

    // Packaged first: when a vendored copy exists it is the one that shipped,
    // and preferring it means a published crate never depends on a path that
    // was not included in it.
    let vendored = manifest.join("nUlakam");
    if vendored.is_dir() {
        return Some(vendored);
    }

    let in_repository = manifest.parent()?.join("nUlakam");
    if in_repository.is_dir() {
        return Some(in_repository);
    }

    None
}

/// Every `.qmz` under `directory`, keyed by its slash-separated virtual path.
fn collect(directory: &Path, prefix: &str, into: &mut BTreeMap<String, PathBuf>) {
    let entries = match std::fs::read_dir(directory) {
        Ok(entries) => entries,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();

        if path.is_dir() {
            collect(&path, &format!("{prefix}/{name}"), into);
        } else if path.extension().is_some_and(|ext| ext == "qmz") {
            // Forward slashes regardless of host, because the key is compared
            // against what the author typed in an import.
            into.insert(format!("{prefix}/{name}"), path);
        }
    }
}
